[Improvement] Handle encryption at rest errors
wireapp/wire-ios-data-model pull request #1020
Opened 2020-08-26 13:42 UTC by johnxnguyen

## What's new in this PR?

### Issues

While encryption at rest is enabled, it is possible to create broken messages in the database.

### Causes

Setting the protobuf data in an instance of `ZMGenericMessageData` may fail for a variety of reasons, but most likely it is because the database key is missing and therefore the protobuf data can't be encrypted. However, this failure is silent, meaning that the data is not encrypted and therefore not stored. This causes the broken message because any call to `underlyingMessage` will always return `nil`.

### Solutions

Propagate errors up the call stack so that the errors can be handled appropriately.

2020-08-26 13:49 UTC, johnxnguyen commented
@typfel I think we need to look at each case where an error is caught and discuss what would be the best way to handle that error. It may also be good to define errors at different layers and map the errors as they pass through the layers, as well as documenting the errors thrown.

2020-08-26 14:06 UTC, johnxnguyen commented on Source/Model/Conversation/ZMConversation+GenericMessage.swift
> +        guard
Here we can map caught errors to a new domain and rethrow them so that callers can properly handle the failure. We can do this for all "append" methods.

2020-08-26 19:26 UTC, typfel commented on Source/Model/Message/ZMAssetClientMessage+FileMessageData.swift
> +                // No op
We should who calls this property, probably some asset strategy. Might need move the setter into separate method which can throw.

2020-08-26 19:27 UTC, typfel commented on Source/Model/Message/ZMAssetClientMessage+UpdateEvent.swift
>              return
This happens inside the event processing so this should not fail due the databaseKey.

2020-08-26 19:29 UTC, typfel commented on Source/Model/Message/ZMAssetClientMessage.swift
> +        try? owner.add(genericMessage)
Yes, this is part of the asset preprocessing which we can re-try at later point when the database key is present.

2020-08-26 19:29 UTC, typfel commented on Source/Model/Message/ZMClientMessage+Editing.swift
> +            try add(genericMessage.serializedData())
Also happens inside the event processing...

2020-08-26 19:30 UTC, typfel commented on Source/Model/Message/ZMClientMessage+LinkPreview.swift
> +        try? add(message.serializedData())
I think this for an incoming link preview update, if so then this should be fine since it's inside the event processing.

2020-08-26 19:33 UTC, typfel commented on Source/Model/Message/ZMClientMessage+LinkPreview.swift
> +                try add(genericMessage.serializedData())
This is part of the outgoing link preview processing, which we can retry at later point if it fails.

2020-08-26 19:34 UTC, typfel commented on Source/Model/Message/ZMClientMessage+Obfuscate.swift
> +        } catch {
Don't remember exactly when we call obfuscate, when some timer fires? Would need check if that can happen in the background.

2020-08-26 19:35 UTC, typfel commented on Source/Model/Message/ZMClientMessage+UpdateEvent.swift
> +                // TODO: Handle?
Should happen inside the event processing

2020-08-31 13:05 UTC, johnxnguyen commented on Source/Model/Message/ZMAssetClientMessage+FileMessageData.swift
> +                // No op
As far as I could find, the setter is never used in production code, only in tests, and that test is about setting the thumbnail id.

2020-08-31 13:14 UTC, johnxnguyen commented on Source/Model/Message/ZMAssetClientMessage+UpdateEvent.swift
>              return
Added an assertion failure.

2020-08-31 13:22 UTC, johnxnguyen commented on Source/Model/Message/ZMAssetClientMessage.swift
> +        try? owner.add(genericMessage)
It's not so clear how we can re-try the processing later, perhaps we can discuss this together?

2020-08-31 13:26 UTC, johnxnguyen commented on Source/Model/Message/ZMClientMessage+LinkPreview.swift
> +        try? add(message.serializedData())
Added an assertion failure.

2020-08-31 13:28 UTC, johnxnguyen commented on Source/Model/Message/ZMClientMessage+LinkPreview.swift
> +                try add(genericMessage.serializedData())
Also here it's not clear how we can retry this.

2020-08-31 13:31 UTC, johnxnguyen commented on Source/Model/Message/ZMClientMessage+Obfuscate.swift
> +        } catch {
It can happen when a `ZMMessageDestructionTimer` fires, or when we delete old ephemerals (happens when coming into the foreground, activating a session, creating a new client message transcoder).

2020-08-31 13:33 UTC, johnxnguyen commented on Source/Model/Message/ZMClientMessage+UpdateEvent.swift
> +                // TODO: Handle?
Added assertion failure.

2020-08-31 13:56 UTC, johnxnguyen commented on Source/Model/Message/ZMAssetClientMessage.swift
> +        try? owner.add(genericMessage)
One thing I noticed is that most of the methods here guard that  `underlyingMessage` is not `nil`. Previously we would only encounter `nil` if the generic message couldn't be created from the serialized data. But now it can happen when the database key is missing. We probably also have to check that usages of `underlyingMessage` also handle the `nil` case appropriately.

2020-09-07 09:14 UTC, johnxnguyen commented on Source/Model/Conversation/ZMConversation+Confirmations.swift
> +                Logging.messageProcessing.warn("Failed to append confirmation. Reason: \(error.localizedDescription)")
Logged warning.

2020-09-07 09:14 UTC, johnxnguyen commented on Source/Model/Message/Composite/CompositeMessageItemContent.swift
> +                Logging.messageProcessing.warn("Failed to append button action. Reason: \(error.localizedDescription)")
Logged warning.

2020-09-07 09:14 UTC, johnxnguyen commented on Source/Model/Message/ConversationMessage+Deletion.swift
> +            Logging.messageProcessing.warn("Failed to append hide message. Reason: \(error.localizedDescription)")
Logged warning.

2020-09-07 09:14 UTC, johnxnguyen commented on Source/Model/Message/ConversationMessage+Deletion.swift
> +            Logging.messageProcessing.warn("Failed delete message for everyone. Reason: \(error.localizedDescription)")
Logged warning.

2020-09-07 09:14 UTC, johnxnguyen commented on Source/Model/Message/ZMAssetClientMessage+Ephemeral.swift
> +                Logging.messageProcessing.warn("Failed to process obfuscated message. Reason: \(error.localizedDescription)")
Logged warning.

2020-09-07 09:14 UTC, johnxnguyen commented on Source/Model/Message/ZMAssetClientMessage+FileMessageData.swift
> +                Logging.messageProcessing.warn("Failed to set thumbnail asset id. Reason: \(error.localizedDescription)")
Logged warning.

2020-09-07 09:14 UTC, johnxnguyen commented on Source/Model/Message/ZMAssetClientMessage.swift
> +            Logging.messageProcessing.warn("Failed to update asset id. Reason: \(error.localizedDescription)")
Logged warning.

2020-09-07 09:14 UTC, johnxnguyen commented on Source/Model/Message/ZMAssetClientMessage.swift
> +            Logging.messageProcessing.warn("Failed to update preprocessed image data. Reason: \(error.localizedDescription)")
Logged warning.

2020-09-07 09:14 UTC, johnxnguyen commented on Source/Model/Message/ZMAssetClientMessage.swift
> +            Logging.messageProcessing.warn("Failed to encrypt asset message data. Reason: \(error.localizedDescription)")
Logged warning.

2020-09-07 09:14 UTC, johnxnguyen commented on Source/Model/Message/ZMClientMessage+LinkPreview.swift
> +            assertionFailure("Failed to set generic message: \(error.localizedDescription)")
Logged warning.

2020-09-07 09:14 UTC, johnxnguyen commented on Source/Model/Message/ZMClientMessage+Obfuscate.swift
> +            Logging.messageProcessing.warn("Failed to merge obfuscated message. Reason: \(error.localizedDescription)")
Logged warning.

2020-09-07 09:14 UTC, johnxnguyen commented on Source/Model/Message/ZMClientMessage+Editing.swift
> +            Logging.messageProcessing.warn("Failed to process message edit. Reason: \(error.localizedDescription)")
Logged warning.

2020-09-07 09:14 UTC, johnxnguyen commented on Source/Model/Message/ZMClientMessage+LinkPreview.swift
> +                Logging.messageProcessing.warn("Failed to link preview image data. Reason: \(error.localizedDescription)")
Logged warning.

2020-09-07 09:14 UTC, johnxnguyen commented on Source/Model/Message/ZMClientMessage+TextMessageData.swift
> +            Logging.messageProcessing.warn("Failed to edit text message. Reason: \(error.localizedDescription)")
Logged warning.

2020-09-07 10:02 UTC, typfel requested changes

2020-09-07 11:15 UTC, johnxnguyen commented on Source/Model/Message/Composite/CompositeMessageItemContent.swift
> +            do {
Yeah I think so. Probably also we want to make everything in the block contingent on the success of the message append.

2020-09-07 11:17 UTC, johnxnguyen commented on Source/Model/Message/Composite/CompositeMessageItemContent.swift
> +            do {
Actually, maybe not.

2020-09-07 11:18 UTC, johnxnguyen commented on Source/Model/Message/Composite/CompositeMessageItemContent.swift
> +            do {
Fixed

2020-09-07 11:18 UTC, johnxnguyen commented on Source/Model/Message/ConversationMessage+Deletion.swift
> +        // TODO [John] Handle?
Moved the do catch to `hideForSelfUser` and only return early in the catch.

2020-09-09 12:33 UTC, typfel commented on Source/Model/Message/Composite/CompositeMessageItemContent.swift
> +            do {
So we should not update `buttonState` after the block. Can you explain why?

2020-09-09 12:36 UTC, typfel commented on Source/Model/Message/Composite/CompositeMessageItemContent.swift
> +            do {
Sorry, GitHub was showing me an outdated diff.

2020-09-09 12:39 UTC, typfel approved these changes
😅

2020-09-09 12:57 UTC, johnxnguyen commented
> 😅

Thanks @typfel , I owe you a beer!

2020-09-10 07:33 UTC, johnxnguyen commented
@zenkins release major

2020-09-10 07:35 UTC, merged