[Feature]: Analytics add UserID
wireapp/wire-ios-data-model pull request #1034
Opened 2020-09-29 12:59 UTC by marcomaddy1982

## What's new in this PR?

in order to identify an user on Analytics we added an unique id in core data for the User object

## Dependencies

JIRA: https://wearezeta.atlassian.net/browse/ZIOS-13750

2020-09-29 13:00 UTC, johnxnguyen commented
Did you mean to set the target branch to `feature/analytics`?

2020-09-29 13:15 UTC, johnxnguyen submitted a review, later dismissed

2020-09-29 13:17 UTC, johnxnguyen requested changes
Please provide a simple test to ensure the self user has the id set when created.

2020-09-29 13:35 UTC, marcomaddy1982 commented
@zenkins release minor

2020-09-29 13:36 UTC, merged

2020-09-29 13:54 UTC, johnxnguyen commented
@marcomaddy1982 did you add the test?

2020-10-02 12:15 UTC, typfel commented on Source/Model/User/ZMUser.m
> +        selfUser.analyticsIdentifier = [[NSUUID UUID] UUIDString];
This would converted into a `transportString`