[Performance] Calculating unread messages
wireapp/wire-ios-data-model pull request #1035
Opened 2020-09-30 09:28 UTC by KaterinaWire

## What's new in this PR?

### Issues

We re-calculate the unread message count on every message insert or timestamp change. This is wasteful in a scenario where we receive x messages in the same conversation, we would then calculate the unread count x times when it's enough to do it once after inserting all the messages.
### Solutions

Mark a conversation as needed to update the unread message counter. After creating or updating all messages from update events, update the unread message counter for all conversations.

## Dependencies

https://wearezeta.atlassian.net/browse/ZIOS-13812

2020-09-30 09:50 UTC, johnxnguyen requested changes
You need to set the flag back to `false` after updating the unread count. Don't forget to assert this behavior with tests.

2020-09-30 12:01 UTC, KaterinaWire commented
> You need to set the flag back to `false` after updating the unread count. Don't forget to assert this behavior with tests.



> You need to set the flag back to `false` after updating the unread count. Don't forget to assert this behavior with tests.

Yes, I missed this part. I assume that the best place to set flag back to `false` in `calculateLastUnreadMessages()`, since we call this method after inserting messages from all events. I added a test to check the behavior of this flag, but now I'm thinking of edge cases for testing.

2020-09-30 12:56 UTC, johnxnguyen approved these changes

2020-09-30 13:02 UTC, typfel requested changes

2020-09-30 13:02 UTC, typfel commented on Source/Public/ZMConversation.h
> +@property (nonatomic) BOOL needsToCalculateUnreadMessages;
I think we would need persist this property otherwise we would lose the state of this flag and not re-calculate the unread messages when we need to.

2020-09-30 13:07 UTC, typfel commented
I experienced that I had an unread count which didn't go away after https://github.com/wireapp/wire-ios-data-model/pull/1031 was merged. 

I would propose that we add back the calculating the unread count in `awakeFromFetch` and `awakeFromInsert` but only if `needsToCalculateUnreadMessages` is `true`.

2020-09-30 14:26 UTC, KaterinaWire commented on Source/Public/ZMConversation.h
> +@property (nonatomic) BOOL needsToCalculateUnreadMessages;
Added this property to CoreData

2020-09-30 14:26 UTC, KaterinaWire commented
> I experienced that I had an unread count which didn't go away after #1031 was merged.
> 
> I would propose that we add back the calculating the unread count in `awakeFromFetch` and `awakeFromInsert` but only if `needsToCalculateUnreadMessages` is `true`.

Done

2020-09-30 15:27 UTC, typfel commented
You've missed a few places where we also call `calculateUnreadMessages()`

`updateTimestampsAfterUpdatingMessage()`
`updateTimestampsAfterInsertingMessage()`
`updateTimestampsAfterDeletingMessage()`

2020-09-30 16:24 UTC, typfel commented on Source/Model/Conversation/ZMConversation+Timestamps.swift
> +    public func calculateLastUnreadMessages() {
No longer needs to be public

2020-09-30 16:34 UTC, typfel commented
Looking good 👍

 Let's also add a test for `calculateLastUnreadMessages(in managedObjectContext:)`

2020-10-01 07:50 UTC, KaterinaWire commented on Source/Model/Conversation/ZMConversation+Timestamps.swift
> +    public func calculateLastUnreadMessages() {
Done

2020-10-01 07:50 UTC, KaterinaWire commented
> Looking good 👍
> 
> Let's also add a test for `calculateLastUnreadMessages(in managedObjectContext:)`

Added a test

2020-10-02 07:19 UTC, typfel commented on Tests/Source/Model/Conversation/ZMConversationTests+UnreadMessages.swift
> +        }
```suggestion
        syncMOC.performGroupedBlockAndWait {
            // given
            let conversation = ZMConversation.insertNewObject(in:self.syncMOC)
            conversation.conversationType = .group
            conversation.remoteIdentifier = UUID.create()
            
           let knock = GenericMessage(content: Knock.with { $0.hotKnock = false })
            let message = ZMClientMessage(nonce: UUID(), managedObjectContext: self.syncMOC)
            do {
                try message.setUnderlyingMessage(knock)
            } catch {
                XCTFail()
            }
            message.serverTimestamp = Date()
            message.visibleInConversation = conversation
            conversation.updateTimestampsAfterUpdatingMessage(message)
            
            XCTAssertTrue(conversation.needsToCalculateUnreadMessages)
            XCTAssertEqual(conversation.estimatedUnreadCount, 0)
            
            // when
            ZMConversation.calculateLastUnreadMessages(in: self.syncMOC)
            XCTAssertTrue(self.syncMOC.saveOrRollback())
            
            // then
            XCTAssertEqual(conversation.estimatedUnreadCount, 1)
            XCTAssertFalse(conversation.needsToCalculateUnreadMessages)
        }
```

I'd propose to only a have single `given, when, then`, because then it's more clear what we are testing in this test.  That `needsToCalculateUnreadMessages` is set to `true` after `conversation.updateTimestampsAfterUpdatingMessage ()` is already tested in another test you added.

2020-10-02 07:56 UTC, typfel commented on Tests/Source/Model/Conversation/ZMConversationTests+Timestamps.swift
> +
Looking at these tests, I think they are testing too many things. We already have other tests for testing that the `estimatedUnreadCount` is increased when calling `calculateLastUnreadMessages()`. What's new and what we should test in isolation is that: 
- `needsToCalculateUnreadMessages` is set to true after inserting a message from an update event.
- `needsToCalculateUnreadMessages` is set to false after calling `calculateLastUnreadMessages()`

2020-10-02 08:44 UTC, KaterinaWire commented on Tests/Source/Model/Conversation/ZMConversationTests+Timestamps.swift
> +
Done. Separated the logic of this test into 2 new tests.

2020-10-02 09:06 UTC, typfel approved these changes

2020-10-02 10:38 UTC, KaterinaWire commented
@zenkins release minor

2020-10-02 10:39 UTC, merged