[Feature]:[WIP] Analytics ID Improvements
wireapp/wire-ios-data-model pull request #1036
Opened 2020-10-02 13:12 UTC by marcomaddy1982

## What's new in this PR?

we are converting the UUID into a transportString

2020-10-02 14:43 UTC, typfel requested changes

2020-10-02 14:43 UTC, typfel commented on Tests/Source/Model/User/ZMUserTests.m
> +- (void)testThatItCanParseLowercaseUUID
This test doesn't exercise the code path where the `analyticsIdentifier` is initialised. We don't need need test that `transportString` generate a lower case UUID representation, that's already tested in `wire-ios-transport`.

2020-10-02 14:52 UTC, billypchan commented on Source/Model/User/ZMUser.m
> +        selfUser.analyticsIdentifier = [[NSUUID UUID] transportString];
It would be clean to create a method like `selfUser.assignAnalyticsIdentifier` and create a test for it.

2020-10-02 14:54 UTC, marcomaddy1982 commented on Source/Model/User/ZMUser.m
> +        selfUser.analyticsIdentifier = [[NSUUID UUID] transportString];
I added a new test, check if it good as well.

2020-10-02 14:54 UTC, billypchan commented on Tests/Source/Model/User/ZMUserTests.m
> +    XCTAssertNotNil(sut.analyticsIdentifier);
It will be nice to test the UUID's format, e.g. regex to check the format of the UUID. And you may write this test in Swift.

2020-10-02 15:09 UTC, typfel commented on Tests/Source/Model/User/ZMUserTests.m
> +    XCTAssertNotNil(sut.analyticsIdentifier);
I don't think we should start testing the `transportString` with regex such tests belong to `wire-ios-transport`.

2020-10-02 15:10 UTC, typfel commented on Tests/Source/Model/User/ZMUserTests.m
> +    XCTAssertNotNil(sut.analyticsIdentifier);
It would enough to verify that the `analyticsIdentifier` can be converted back into a Date with calling `[NSDate dateFromTransportString:]`

2020-10-05 07:45 UTC, typfel commented on Tests/Source/Model/User/ZMUserTests.m
> +- (void)testThatAnalyticsIdentifierCanBeConvertedBack
```suggestion
- (void)testThatAnalyticsIdentifierIsEncodedAsUUIDTransportString
```

2020-10-05 07:47 UTC, typfel approved these changes

2020-10-05 08:01 UTC, marcomaddy1982 commented
@zenkins release patch

2020-10-05 08:02 UTC, merged