[Refactor] Decouple change detection
wireapp/wire-ios-data-model pull request #1039
Opened 2020-10-07 12:46 UTC by johnxnguyen

## What's new in this PR?

This PR is part of ongoing work to refactor the `NotificationDispatcher` such that it can operate in an "eco" mode which favors speed over detail.

### Issues

It is difficult to change the change detection logic in the `NotificationDispatcher`. 

### Causes

Change detection is built right into the `NotificationDispatcher` in a highly coupled way.

### Solutions

Decouple the change detection into a separate class. The idea is that in the future we can easily swap in a different "eco" change detector.

2020-10-07 13:18 UTC, typfel requested changes

2020-10-07 13:18 UTC, typfel commented on Source/Notifications/Change detection/DetailedChangeDetector.swift
> +            detectChangesCausedByChangeInObjects(updatedObject: object, knownKeys: changedKeys)
Why is the argument called `knownKeys` and not `changedKeys`?

2020-10-07 13:18 UTC, typfel commented on Source/Notifications/Change detection/DetailedChangeDetector.swift
> +    private func detectChangesCausedByChangeInObjects(updatedObject: ZMManagedObject, knownKeys: Set<String>) {
I think it would be easier to follow the code if this method returns the result instead of directly altering `allChanges`, because it's called from `detectChanges(for:)` and there we update `allChanges` at the end and it's surprising that we modify `allChanges` also while calculating the changes.

2020-10-07 13:24 UTC, johnxnguyen commented on Source/Notifications/Change detection/DetailedChangeDetector.swift
> +            detectChangesCausedByChangeInObjects(updatedObject: object, knownKeys: changedKeys)
Not sure, so far I've just moved code. I intend to refactor and clean up this logic too (and also elsewhere because it's super hard to follow) but didn't want to bloat this PR any further.

2020-10-07 13:25 UTC, johnxnguyen commented on Source/Notifications/Change detection/DetailedChangeDetector.swift
> +    private func detectChangesCausedByChangeInObjects(updatedObject: ZMManagedObject, knownKeys: Set<String>) {
Yep I agree 👍

2020-10-09 07:18 UTC, typfel approved these changes

2020-10-09 07:23 UTC, merged