remove duplicated executeFetchRequestOrAssert implementation
wireapp/wire-ios-data-model pull request #1055
Opened 2020-11-03 17:33 UTC by billypchan

## What's new in this PR?

### Issues

When building the project with XCode 12, failed with error `executeFetchRequestOrAssert` no longer accepts an optional parameter and return optional type

### Causes

Utilities also have `executeFetchRequestOrAssert` implemetation without `nonnull` signatures.

### Solutions

Removed the duplicated implementation in Data model. Use Swift version `fetchOrAssert(request::)`

2020-11-04 15:08 UTC, typfel requested changes
I suggest marking `sortedFetchRequest()`  and `sortedFetchRequest(with:)` as returning `nonnull `.

2020-11-04 15:19 UTC, billypchan commented
> I suggest marking `sortedFetchRequest()` and `sortedFetchRequest(with:)` as returning `nonnull `.

I am converting that to Swift.

2020-11-04 15:59 UTC, typfel requested changes

2020-11-04 15:59 UTC, typfel commented on Source/Model/ZMManagedObject.m
>  + (NSFetchRequest *)sortedFetchRequestWithPredicate:(NSPredicate *)predicate
You forgot to delete this method

2020-11-04 15:59 UTC, typfel commented on Source/Model/ZMManagedObject+Internal.h
>  + (nullable NSFetchRequest *)sortedFetchRequestWithPredicateFormat:(nonnull NSString *)format, ...;
Let's make this one `nonnull` for completeness?

```suggestion
+ (nonnull NSFetchRequest *)sortedFetchRequestWithPredicateFormat:(nonnull NSString *)format, ...;
```

2020-11-04 16:01 UTC, KaterinaWire commented on Source/Model/Conversation/ZMConversation+Patches.swift
> +        guard let conversations = moc.executeFetchRequestOrAssert(groupConversationsFetch) as? [ZMConversation] else {
Why don't use `fetchOrAssert` method here?

2020-11-04 16:02 UTC, KaterinaWire commented on Source/Model/Conversation/ZMConversation+Patches.swift
> +        guard let conversations = moc.executeFetchRequestOrAssert(request) as? [ZMConversation] else {
Why don't use fetchOrAssert method here too?

2020-11-04 16:29 UTC, billypchan commented on Source/Model/ZMManagedObject.m
>  + (NSFetchRequest *)sortedFetchRequestWithPredicate:(NSPredicate *)predicate
I undid this change, will fix in a new PR.

2020-11-04 17:01 UTC, billypchan commented on Source/Model/Conversation/ZMConversation+Patches.swift
> +        guard let conversations = moc.executeFetchRequestOrAssert(groupConversationsFetch) as? [ZMConversation] else {
fixed

2020-11-04 17:01 UTC, billypchan commented on Source/Model/Conversation/ZMConversation+Patches.swift
> +        guard let conversations = moc.executeFetchRequestOrAssert(request) as? [ZMConversation] else {
fixed

2020-11-05 07:29 UTC, KaterinaWire approved these changes

2020-11-05 07:45 UTC, typfel commented on Source/Model/ZMManagedObject.m
>  + (NSFetchRequest *)sortedFetchRequestWithPredicate:(NSPredicate *)predicate
Ok will you merge that PR into this branch? Because that will be a another breaking change and I suppose you don't want to do the release train twice.

2020-11-05 07:46 UTC, typfel commented
> I am converting that to Swift. But I found there is a subclassing issue in the test and I will open a new PR for that.

Why not simply annotate the Objective-C version if you have subclassing issues after the Swift conversion?

2020-11-05 08:49 UTC, billypchan commented on Source/Model/ZMManagedObject.m
>  + (NSFetchRequest *)sortedFetchRequestWithPredicate:(NSPredicate *)predicate
the PR is here:
https://github.com/wireapp/wire-ios-data-model/pull/1056

2020-11-05 08:53 UTC, billypchan commented
> > I am converting that to Swift. But I found there is a subclassing issue in the test and I will open a new PR for that.
> 
> Why not simply annotate the Objective-C version if you have subclassing issues after the Swift conversion?

I found `NSManagedObjectContext` has some subclasses would override `sortedFetchRequest`. It would be better do not increase the scope of this PR.

2020-11-09 10:39 UTC, typfel requested changes
Looks good! just some nitpicking.

2020-11-09 10:39 UTC, typfel commented on Source/Model/UserClient/UserClient+Patches.swift
> +        let allClients = moc.fetchOrAssert(request: request) as? [UserClient]
Do a guard return here?

2020-11-09 10:39 UTC, typfel commented on Cartfile.resolved
> +github "wireapp/wire-ios-utilities" "38.0.0"
Remember that you need to do a major releases from `wire-ios-utilities` and up

2020-11-09 10:39 UTC, typfel commented on Source/Model/Conversation/Team+Patches.swift
> +        }
Clean up indentation?

2020-11-09 11:18 UTC, typfel approved these changes

2020-11-09 14:54 UTC, billypchan commented
@zenkins release major

2020-11-09 14:55 UTC, merged