[Feature] Define a Feature entity
wireapp/wire-ios-data-model pull request #1066
Opened 2020-11-16 07:06 UTC by KaterinaWire

## What's new in this PR?

### Issues
This PR is a part of the` Enforce App-Lock` feature. To be able to configure features, we will fetch it from BE and store them in Core Data.

### Solutions
Define a Feature entity that will contain feature configurations.

2020-11-17 10:21 UTC, johnxnguyen commented on Source/Model/FeatureConfig/Feature.swift
> +    @NSManaged public var status: String
In another PR I discussed having a `Status` enum. If we defined it in data model, we could also use it here to give this a stronger type.

2020-11-17 12:04 UTC, johnxnguyen requested changes

2020-11-17 12:04 UTC, johnxnguyen commented on Source/Model/FeatureConfig/Feature.swift
> +    @NSManaged public var statusValue: String
Better to make `statusValue` private since you have a custom accessor.

2020-11-17 12:04 UTC, johnxnguyen commented on Source/Model/FeatureConfig/Feature.swift
> +}
Better to declare this within `Feature`, e.g so you would access it like `Feature.Status.enabled`

2020-11-17 12:10 UTC, KaterinaWire commented on Source/Model/FeatureConfig/Feature.swift
> +}
Done

2020-11-17 12:11 UTC, KaterinaWire commented on Source/Model/FeatureConfig/Feature.swift
> +    @NSManaged public var statusValue: String
Fixed

2020-11-17 12:11 UTC, KaterinaWire commented on Source/Model/FeatureConfig/Feature.swift
> +    @NSManaged public var status: String
Fixed

2020-11-17 12:28 UTC, johnxnguyen commented on Source/Model/FeatureConfig/Feature.swift
> +            return Status(rawValue: statusValue) ?? .disabled
The only way that we would get a `nil` value here is if the case names change while there exists values in the database. In which case, that would be a programmer error. Do you think in case it is better to intentionally crash (with a message) rather than disable the feature?

2020-11-17 14:04 UTC, KaterinaWire commented on Source/Model/FeatureConfig/Feature.swift
> +            return Status(rawValue: statusValue) ?? .disabled
Do you mean to have a third case as .unknown and manage it somewhere?

2020-11-17 14:11 UTC, johnxnguyen commented on Source/Model/FeatureConfig/Feature.swift
> +            return Status(rawValue: statusValue) ?? .disabled
I mean something like:

```swift
guard let status = Status(rawValue: statusValue) else { fatalError() }
return status
```

The question is whether returning `disabled` as a fallback could ever lead to issues. I can't really think of any though.

2020-11-17 14:12 UTC, johnxnguyen approved these changes

2020-11-18 07:34 UTC, johnxnguyen commented on Source/Model/FeatureConfig/Feature.swift
> +            return status
This was more intended as a topic of discussion, I'm not sure whether it is better to intentionally crash or provide some fallback.

2020-11-18 09:33 UTC, johnxnguyen commented on Source/Model/FeatureConfig/Feature.swift
> +            return status
If we do crash, then we should provide a message including the `statusValue` as it would be needed to know how to solve the issue should it occur.

2020-11-18 12:23 UTC, KaterinaWire commented on Source/Model/FeatureConfig/Feature.swift
> +            return status
Added logs

2020-11-18 14:28 UTC, marcomaddy1982 commented on Source/Model/FeatureConfig/Feature.swift
> +   public enum Status: String, Codable {
I like the idea to have an enum for the Status, even if it has (for now) just two value. 👍

2020-11-18 14:28 UTC, marcomaddy1982 approved these changes

2020-11-18 14:38 UTC, johnxnguyen requested changes

2020-11-18 14:38 UTC, johnxnguyen commented on Source/Model/FeatureConfig/Feature.swift
> +            return status
Instead of logging an error, pass a message to the fatalError:

```swift
fatalError("Failed to decode Feature statusValue: \(statusValue)")
```

This will allow us to see the message in the crash log (I think) so we wouldn't need to get the logs to check the value.

2020-11-18 16:08 UTC, KaterinaWire commented on Source/Model/FeatureConfig/Feature.swift
> +            return status
Done

2020-11-19 07:35 UTC, johnxnguyen approved these changes

2020-11-19 09:26 UTC, merged

2020-11-19 10:51 UTC, johnxnguyen commented
@KaterinaWire don't forget to delete this branch.