[Feature]: EAR and export backup
wireapp/wire-ios-data-model pull request #1068
Opened 2020-11-16 09:34 UTC by marcomaddy1982

## What's new in this PR?

In the version of the app without the EAR when a user start a backup the following steps are executed:

1. User initiates backup from the settings
2. Enter password for the backup
3. We generate the backup
4 Copy local store
5 Put the backup into an encrypted container using the password entered in step 2

with the introduction of the EAR and when it is enabled there is an additional layer of encryption on the database. When the user will create a new backup, if the EAR is enabled we have first decrypt the EAR before put the backup into an encrypted container using the password he/she previously entered. This mean that with the EAT we will have the following steps when a backup is created

1. User initiates backup from the settings
2. Enter password for the backup
3. We generate the backup
4 Copy local store
**5 Decrypt local store if necessary (encryption keys should already be available)**
6 Put backup into an encrypted container using the password entered in step 2

2020-11-16 10:48 UTC, typfel requested changes

2020-11-16 10:48 UTC, typfel commented on Source/ManagedObjectContext/StorageStack+Backup.swift
> +                } catch {
You should not catch error because we want it to bubble up so that whole backup operation fails.

2020-11-16 10:48 UTC, typfel commented on Source/ManagedObjectContext/StorageStack+Backup.swift
> +                    try context.disableEncryptionAtRest(encryptionKeys: encryptionKeys)
How about doing this only if `context.encryptMessagesAtRest` is `true`?

2020-11-16 10:48 UTC, typfel commented on Source/ManagedObjectContext/ManagedObjectContextDirectory+EncryptionAtRest.swift
> +    func getEncryptionKeys() throws -> EncryptionKeys {
I don't we need another accessor for the encryption keys since `uiContext` is a public property and exposing like this is inviting users to use it on the wrong context (It will crash unless used from the main context).

2020-11-16 10:48 UTC, typfel commented on Source/ManagedObjectContext/StorageStack+Backup.swift
> +                try markAsImported(coordinator: coordinator,
I think this name no longer describing what the method does. Maybe something like `prepareStoreForBackup()`?

2020-11-16 10:58 UTC, johnxnguyen requested changes

2020-11-16 10:58 UTC, johnxnguyen commented on Source/ManagedObjectContext/StorageStack+Backup.swift
> +                    try context.disableEncryptionAtRest(encryptionKeys: encryptionKeys)
Additionally, we should probably throw an error when EAR is enabled but encryption keys were not passed to the method. There's no point creating a backup if we can't decrypt it first.

2020-11-16 10:58 UTC, johnxnguyen commented on Source/ManagedObjectContext/StorageStack+Backup.swift
> +        encryptionKeys: EncryptionKeys? = nil,
Don't forget to document the new argument.

2020-11-16 10:58 UTC, johnxnguyen commented on Source/ManagedObjectContext/StorageStack+Backup.swift
> +        encryptionKeys: EncryptionKeys? = nil,
Also... just wondering why we need to pass the encryption keys as an argument?

2020-11-16 13:46 UTC, marcomaddy1982 commented on Source/ManagedObjectContext/StorageStack+Backup.swift
> +        encryptionKeys: EncryptionKeys? = nil,
Cause we don't have here direct access to the `activeUserSession`, so we retrieve them in the SE (`SessionManager+Backup`) and we inject here. Do you have a better way in mind?

2020-11-16 13:48 UTC, marcomaddy1982 commented on Source/ManagedObjectContext/StorageStack+Backup.swift
> +                    try context.disableEncryptionAtRest(encryptionKeys: encryptionKeys)
I will add an `throw` error for the case you mentioned but right before the start of the backup.

2020-11-16 14:00 UTC, marcomaddy1982 commented
@typfel @johnxnguyen I guess I have addressed all your comments. Thanks 👍

2020-11-16 14:09 UTC, typfel commented on Source/ManagedObjectContext/StorageStack+Backup.swift
> +                    try context.disableEncryptionAtRest(encryptionKeys: encryptionKeys)
> I will add an `throw` error for the case you mentioned but right before the start of the backup.

Hmm why not do check here? Then you also don't need to expose the `getEncryptionKeys()` since then you could access the encryption keys directly on the context `uiContext.encryptionsKeys`.

2020-11-16 15:35 UTC, typfel requested changes

2020-11-16 15:35 UTC, typfel commented on Source/ManagedObjectContext/NSManagedObjectContext+EncryptionAtRest.swift
> +    public func getEncryptionKeys() throws -> EncryptionKeys {
Doesn't need to be public anymore

2020-11-16 15:36 UTC, typfel commented
We are still missing tests

2020-11-17 07:33 UTC, johnxnguyen commented on Source/ManagedObjectContext/StorageStack+Backup.swift
> +        encryptionKeys: EncryptionKeys? = nil,
I thought you could get the encryption keys from the context?

2020-11-17 08:03 UTC, typfel commented on Source/ManagedObjectContext/StorageStack+Backup.swift
> +        encryptionKeys: EncryptionKeys? = nil,
@johnxnguyen the only context available here is a temporary context we create for the copied local store, since we create the context here it won't have the encryption keys set.

2020-11-17 08:07 UTC, johnxnguyen commented on Source/ManagedObjectContext/StorageStack+Backup.swift
> +            if let encryptionKeys = encryptionKeys {
A `guard` would make this a bit more readable:

```swift
guard let encryptionKeys = encryptionKeys else { throw BackupError.missingEAREncryptionKey }
```

2020-11-17 09:53 UTC, marcomaddy1982 commented
> We are still missing tests

Done

2020-11-17 09:53 UTC, marcomaddy1982 commented on Source/ManagedObjectContext/StorageStack+Backup.swift
> +            if let encryptionKeys = encryptionKeys {
Done

2020-11-17 10:54 UTC, johnxnguyen approved these changes

2020-11-17 10:56 UTC, typfel requested changes

2020-11-17 10:56 UTC, typfel commented on Tests/Source/ManagedObjectContext/StorageStackTests_Backup.swift
> +    func testThaItNotFindsTheStorage_WhenEARIsEnabledAndEncryptionKeysAreNil() throws {
Suggestion: `testThatItFailsWhenEARIsEnabledAndEncryptionKeysAreNil`

2020-11-17 10:56 UTC, typfel commented on Tests/Source/ManagedObjectContext/StorageStackTests_Backup.swift
> +    func testThaItFindsTheStorage_WhenEARIsDisabledAndEncryptionKeysAreNil() throws {
Isn't this already coved by `testThatItFindsTheStorageWithCorrectAccountIdentifier`?

2020-11-17 10:56 UTC, typfel commented on Tests/Source/ManagedObjectContext/StorageStackTests_Backup.swift
> +    func testThatItFindsTheStorage_WhenEARIsEnableAndEncryptionKeysAreValid() throws {
We are not testing that the backup has encryption at rest disabled. I think we need to open the backup and verify that `encryptMessagesAtRest` is `false`. 

You can look at `testThatItMarksStoreAsBackupWhenExporting` for how this is done.

2020-11-17 10:56 UTC, typfel commented on Tests/Source/ManagedObjectContext/StorageStackTests_Backup.swift
> +    func testThatItFindsTheStorage_WhenEARIsEnableAndEncryptionKeysAreValid() throws {
Also if we are testing that EAR was disabled int the backup I would change the name to something like:
`testThatItDisablesEncryptionAtRest_WhenEARIsEnableAndEncryptionKeysAreValid`

2020-11-17 10:56 UTC, typfel commented on Tests/Source/ManagedObjectContext/StorageStackTests_Backup.swift
> +    func testThatItPreservesOriginalDataAfterBackup_WhenEARIsEnableAndEncryptionKeysAreValid() {
Do we really need this test? I think `testThatItPreservesOriginalDataAfterBackup` is enough, since it's testing that we operate on a local store copy and that also applies for the EAR case.

2020-11-17 10:56 UTC, typfel commented on Tests/Source/ManagedObjectContext/StorageStackTests_Backup.swift
> +    func testThatItPreservesOriginaDataAfterBackupIfStackIsNotActive_WhenEARIsDisabledAndEncryptionKeysAreNil() throws {
Do we really need this test? See previous comment.

2020-11-17 10:59 UTC, marcomaddy1982 commented on Tests/Source/ManagedObjectContext/StorageStackTests_Backup.swift
> +    func testThaItFindsTheStorage_WhenEARIsDisabledAndEncryptionKeysAreNil() throws {
Yes Right that actually it is the same scenario. I will remove this one.

2020-11-17 11:10 UTC, marcomaddy1982 commented on Tests/Source/ManagedObjectContext/StorageStackTests_Backup.swift
> +    func testThatItPreservesOriginalDataAfterBackup_WhenEARIsEnableAndEncryptionKeysAreValid() {
Why not, I mean we are testing that after exporting a db with EAR enabled no weird stuffs are happening in the original data. In the `testThatItPreservesOriginalDataAfterBackup` the EAR is disable so we are not exactly in the came condition.  Anyway if you prefer we can remove.

2020-11-17 11:11 UTC, marcomaddy1982 commented on Tests/Source/ManagedObjectContext/StorageStackTests_Backup.swift
> +    func testThatItPreservesOriginaDataAfterBackupIfStackIsNotActive_WhenEARIsDisabledAndEncryptionKeysAreNil() throws {
See previous comment.

2020-11-17 11:45 UTC, typfel commented on Tests/Source/ManagedObjectContext/StorageStackTests_Backup.swift
> +    func testThatItPreservesOriginalDataAfterBackup_WhenEARIsEnableAndEncryptionKeysAreValid() {
It's true that is not exactly the same condition but for this test to fail we would need to open and modify or delete  original local store which is also covered by first test.

I'm very cautious about having tests which cover the same scenario because it:
- Makes it painful when changing the behaviour of the code, multiple tests break when one behaviour is changed.
- Makes it unclear what is broken because multiple tests will always break together.

2020-11-17 11:52 UTC, marcomaddy1982 commented on Tests/Source/ManagedObjectContext/StorageStackTests_Backup.swift
> +    func testThatItPreservesOriginalDataAfterBackup_WhenEARIsEnableAndEncryptionKeysAreValid() {
Ok, I got your point. Makes sense. I'm going to remove them.

2020-11-17 13:10 UTC, marcomaddy1982 commented on Tests/Source/ManagedObjectContext/StorageStackTests_Backup.swift
> +    func testThatItPreservesOriginaDataAfterBackupIfStackIsNotActive_WhenEARIsDisabledAndEncryptionKeysAreNil() throws {
Done.

2020-11-17 13:10 UTC, marcomaddy1982 commented on Tests/Source/ManagedObjectContext/StorageStackTests_Backup.swift
> +    func testThatItPreservesOriginalDataAfterBackup_WhenEARIsEnableAndEncryptionKeysAreValid() {
Done.

2020-11-17 13:25 UTC, typfel approved these changes

2020-11-17 14:23 UTC, merged