[Refactor] Modify enqueueBackendRefresh() to refresh  features
wireapp/wire-ios-data-model pull request #1082
Opened 2020-12-03 22:00 UTC by KaterinaWire

## What's new in this PR?

### Issues

We currently have an `enqueueBackendRefresh()` method that can trigger a BE to update the feature. Since we don't have any feature in the new entity of Core data, we should create a new default  feature and then trigger BE to update it.

2020-12-04 06:25 UTC, typfel requested changes

2020-12-04 06:25 UTC, typfel commented on Source/Model/Conversation/Team+Feature.swift
> +                let defaultInstance = try? Feature.AppLock().store(for: self, in: context)
Wouldn't we need to somehow associate this is new `Feature` instance with `applock`? For example If I call `enqueueBackendRefresh(for .applock)` twice It would create two default instances which I assume is not good.

2020-12-04 10:40 UTC, KaterinaWire commented on Source/Model/Conversation/Team+Feature.swift
> +                let defaultInstance = try? Feature.AppLock().store(for: self, in: context)
The default instance will only be for the `applock` feature (`Feature.AppLock()`).
After our call, I changed the `store(for: self, in: context)` method. This method is now just adding a new feature to Core Data.

2020-12-04 10:51 UTC, typfel commented on Source/Model/Conversation/Team+Feature.swift
> +                let defaultInstance = try? Feature.AppLock().store(for: self, in: context)
I thought we would remove the `if else` here since this logic is already in `Feature.createOrUpdate()`

2020-12-06 20:21 UTC, KaterinaWire commented on Source/Model/Conversation/Team+Feature.swift
> +                let defaultInstance = try? Feature.AppLock().store(for: self, in: context)
I noticed that `Feature.createOrUpdate() `method updates the existing feature with default value or creates a new one.
If I remove ` if else` and keep like this:
```
switch name {
            case .appLock:
                let defaultInstance = try? Feature.AppLock().store(for: self, in: context)
                defaultInstance?.needsToBeUpdatedFromBackend = true
            }
```
It will override the existing feature (or create a new one) with a default value and mark it as `needsToBeUpdatedFromBackend`.
I don't like this idea to override the existing feature.

2020-12-07 06:32 UTC, typfel commented on Source/Model/Conversation/Team+Feature.swift
> +                let defaultInstance = try? Feature.AppLock().store(for: self, in: context)
Ok makes sense. I'll approve this now, maybe in a future PR it makes sense to add a method like `Feature.fetchOrCreate(name:context)` which can do this logic in a generic way without switching over all features.

2020-12-07 06:32 UTC, typfel approved these changes

2020-12-07 12:16 UTC, KaterinaWire commented on Source/Model/Conversation/Team+Feature.swift
> +                let defaultInstance = try? Feature.AppLock().store(for: self, in: context)
@typfel Yes, good point. I've made changes to this PR after your approval.

2020-12-07 12:18 UTC, David-Henner commented on Source/Model/FeatureConfig/Feature.swift
> +        require(results.count <= 1, "More than instance for feature: \(name.rawValue)")
```suggestion
        require(results.count <= 1, "More than one instance for feature: \(name.rawValue)")
```

2020-12-07 12:18 UTC, David-Henner commented on Source/Model/FeatureConfig/Feature.swift
> +                                     config: try? JSONEncoder().encode(defaultInstance.config),
should there be some error handling in case of encoding errors?

2020-12-07 14:45 UTC, KaterinaWire commented on Source/Model/FeatureConfig/Feature.swift
> +                                     config: try? JSONEncoder().encode(defaultInstance.config),
Yes, make sense.
Done

2020-12-07 15:24 UTC, David-Henner approved these changes

2020-12-07 15:31 UTC, merged