[Refactor] Needs to inform user that feature has been changed
wireapp/wire-ios-data-model pull request #1085
Opened 2020-12-07 07:30 UTC by KaterinaWire

## What's new in this PR?

According to the design flow
(https://zpl.io/bArgMpp or zpl://screen?sid=5fbbd5b02956135e8e9f3849&pid=5f0f1143f783828d19da7721)

we should provide a warning screen that feature has been changed. 
I added a `needToInformUserOfFeatureChange` flag to the Feature. This value would be set to `true` when we know there has been a change, and it would be set to `false` when the user has acknowledged the change.

2020-12-07 07:40 UTC, typfel commented
I'm missing the part where you set the `needToInformUserOfFeatureChange` to `true`.

2020-12-07 10:15 UTC, marcomaddy1982 commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +    public var needsToInformUserOfFeatureChange: Bool {
Could we call this just something like `isFeatureChanged`?  i mean i don't think that is so important to who we are informing :-).

2020-12-07 10:51 UTC, typfel commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +    public var needsToInformUserOfFeatureChange: Bool {
We have  many properties in data model named like`needsTo...`, like: 
- `needsToBeUpdatedFromBackend`
- `needsToNotifyUser`
- `needsToUploadSignalingKeys`

So I think the naming follows existing conventions in this case.

2020-12-07 10:53 UTC, marcomaddy1982 commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +    public var needsToInformUserOfFeatureChange: Bool {
Ok, thanks for the clarification.

2020-12-09 06:51 UTC, KaterinaWire commented
> I'm missing the part where you set the `needToInformUserOfFeatureChange` to `true`.

@typfel In this PR: https://github.com/wireapp/wire-ios-request-strategy/pull/262

2020-12-09 06:52 UTC, KaterinaWire commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +    public var needsToInformUserOfFeatureChange: Bool {
I renamed to `needsToNotifyUser`.

2020-12-09 16:01 UTC, KaterinaWire commented
> > I'm missing the part where you set the `needToInformUserOfFeatureChange` to `true`.
> 
> @typfel In this PR: [wireapp/wire-ios-request-strategy#262](https://github.com/wireapp/wire-ios-request-strategy/pull/262)

@typfel I closed the PR in the request strategy and add a `didSet` block to the `configData` property.

2020-12-10 07:21 UTC, marcomaddy1982 commented on Source/Model/FeatureConfig/Feature.swift
> +                needsToNotifyUser = true
this could just be 

`needsToNotifyUser = oldConfig?.enforceAppLock != newConfig?.enforceAppLock`

2020-12-10 07:27 UTC, marcomaddy1982 commented on Source/Model/FeatureConfig/Feature.swift
> +    @NSManaged var needsToNotifyUser: Bool
so does it to be `internal` now?

2020-12-10 08:10 UTC, typfel requested changes

2020-12-10 08:10 UTC, typfel commented on Source/Model/FeatureConfig/Feature.swift
> +            let oldConfig = try? decoder.decode(Feature.AppLock.Config.self, from: oldValue)
You can't assume that this is always going to be a `.applock` config. Perhaps one option would be to switch on the `name` and delegate to a static method on the `AppLock` struct.

`static func needsToNotifyUserOnConfigUpdate(old: Config, new: Config) -> Bool`

In my previous comment on the request-strategy PR  I missed that this is not the decoded config so it's a bit unfortunate that we have to encode & decode the config so many times.

2020-12-10 08:10 UTC, typfel commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +    var needsToNotifyUserOfFeatureChange: Bool { get set }
Should we also rename this to `needsToNotifyUser`?

2020-12-10 08:10 UTC, typfel commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +        public var needsToNotifyUserOfFeatureChange: Bool
Couldn't you remove this property? Seems like `AppLockController. needsToNotifyUserOfFeatureChange` reads the value directly from `Feature.needsToNotifyUser`.

2020-12-10 11:04 UTC, KaterinaWire commented on Source/Model/FeatureConfig/Feature.swift
> +                needsToNotifyUser = true
I think we should set  `needsToNotifyUser ` to `false` only when the user confirms it from the UI.
A case is possible when there will be 2 requests one after another in a short period of time (before the user is informed). The first time it will set the `true` and the second time it will set `false`. So you can lose the "state" of informing the user.

2020-12-10 11:12 UTC, KaterinaWire commented on Source/Model/FeatureConfig/Feature.swift
> +    public var configData: Data? {
`@NSManaged` not allowed on observing properties

2020-12-10 11:13 UTC, typfel commented on Source/Model/FeatureConfig/Feature.swift
> +    public var configData: Data? {
So this approach doesn't work then?

2020-12-10 11:23 UTC, KaterinaWire commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +    var needsToNotifyUserOfFeatureChange: Bool { get set }
Done

2020-12-10 11:23 UTC, KaterinaWire commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +        public var needsToNotifyUserOfFeatureChange: Bool
Yes.
Removed

2020-12-10 11:30 UTC, KaterinaWire commented on Source/Model/FeatureConfig/Feature.swift
> +    public var configData: Data? {
It works. I have a test to check it:
`testThatItUpdatesNeedsToNotifyUserFlag_IfEnforceAppLockHasBeenChanged() `

2020-12-10 11:34 UTC, KaterinaWire commented on Source/Model/FeatureConfig/Feature.swift
> +    @NSManaged var needsToNotifyUser: Bool
Yes. We will not directly get or set this value from the UI.
We will set this value from the `didSet` block of the `configData` property. 
And to get this value, `AppLockController` has `needsToNotifyUser`.

2020-12-10 12:30 UTC, KaterinaWire commented on Source/Model/FeatureConfig/Feature.swift
> +            let oldConfig = try? decoder.decode(Feature.AppLock.Config.self, from: oldValue)
Yes, good point, this should be applied only for `.applock`. I added a switch.
But I have doubts about the static method:
1.  We will only check for changes in the `enforceAppLock `.
2. I think we should only set `needsToNotifyUser` to `true`. `False` should be set from the UI when the user confirms it.

2020-12-10 12:42 UTC, typfel commented on Source/Model/FeatureConfig/Feature.swift
> +            let oldConfig = try? decoder.decode(Feature.AppLock.Config.self, from: oldValue)
```
var updateConfig: Config {
    didSet {
          guard !needsToNotifyUser else { return }
          
          var notify
          switch name {
                case .appLock:
                notify = AppLock.needsToNotifyUserOnConfigUpdate(old: oldConfig, new: newConfig) 
                default:
                notify = false
          }

          needsToNotifyUser = notify
    }
}

static func needsToNotifyUserOnConfigUpdate(old: Config, new: Config) -> Bool {
     return old.enforceAppLock != new.enforceAppLock
}
```

This is essentially the same, I think it would be nice though if feature specific behaviour is kept in their respective class/struct.

2020-12-14 07:20 UTC, johnxnguyen commented on Source/Model/FeatureConfig/AppLock/Feature.AppLock.swift
> +        }
Why do we need this setter? Is this how we would set the value to `false` when the user acknowledges the change?

2020-12-14 10:52 UTC, KaterinaWire commented on Source/Model/FeatureConfig/AppLock/Feature.AppLock.swift
> +        }
I updated this PR after our call

2020-12-14 11:05 UTC, typfel approved these changes

2020-12-14 11:12 UTC, johnxnguyen requested changes

2020-12-14 11:12 UTC, johnxnguyen commented on Tests/Source/Model/FeatureConfiguration/FeatureTests.swift
> +    func testThatItUpdatesNeedsToNotifyUserFlag_IfEnforceAppLockHasBeenChanged() {
We should test also the other way, that enforce app lock was true then changed to false.

2020-12-14 11:40 UTC, KaterinaWire commented on Tests/Source/Model/FeatureConfiguration/FeatureTests.swift
> +    func testThatItUpdatesNeedsToNotifyUserFlag_IfEnforceAppLockHasBeenChanged() {
Done

2020-12-14 11:43 UTC, johnxnguyen approved these changes

2020-12-14 12:34 UTC, merged