[Refactor] Keychain migration for applock
wireapp/wire-ios-data-model pull request #1086
Opened 2020-12-08 12:26 UTC by KaterinaWire

## What's new in this PR?

### Issues

We store custom passcode and enabled status for applock per device. This is an issue now, because applock is a team feature, which means we should store applock configurations for each account.

### Solutions

Store custom passcode and enabled status for applock for each account. We also need to migrate keychain values after making a reales with these changes.

2020-12-09 06:54 UTC, typfel requested changes

2020-12-09 06:54 UTC, typfel commented on Source/ManagedObjectContext/NSManagedObjectContext+AppLock.swift
> +    internal(set) public var appLock: Bool {
Let's name this so that it's clear hat we are dealing with a boolean value, for example `isAppLockEnabled`

2020-12-09 06:54 UTC, typfel commented on Source/Model/User/ZMUser+Applock.swift
> +            return self.managedObjectContext?.appLock ?? false
```suggestion
            return managedObjectContext?.appLock ?? false
```

2020-12-09 06:54 UTC, typfel commented on Source/Model/User/ZMUser+Applock.swift
> +            self.managedObjectContext?.appLock = newValue
```suggestion
            managedObjectContext?.appLock = newValue
```

2020-12-09 06:54 UTC, typfel commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +extension AppLockController {
Let's move these migration related methods to a separate struct inside the the `/patches` directory so that it clear that won't be actively in use.

2020-12-09 06:54 UTC, typfel commented on Source/Utilis/Keychain/PasscodeKeychainItem.swift
> +public extension PasscodeKeychainItem {
Also move this migration related code to a struct in the `/patches` directory.

2020-12-09 11:15 UTC, KaterinaWire commented on Source/ManagedObjectContext/NSManagedObjectContext+AppLock.swift
> +    internal(set) public var appLock: Bool {
Done

2020-12-09 11:16 UTC, KaterinaWire commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +extension AppLockController {
Moved

2020-12-09 11:16 UTC, KaterinaWire commented on Source/Utilis/Keychain/PasscodeKeychainItem.swift
> +public extension PasscodeKeychainItem {
Moved

2020-12-09 11:19 UTC, typfel approved these changes

2020-12-09 12:10 UTC, billypchan commented on Patches/PersistedDataPatches+Directory.swift
> +        PersistedDataPatch(version: "234.0.0", block: TransferApplockKeychain.migrateKeychainItems) //TODO: katerina check the version
the version is checked? we can remove the comment.

2020-12-09 13:13 UTC, KaterinaWire commented on Patches/PersistedDataPatches+Directory.swift
> +        PersistedDataPatch(version: "234.0.0", block: TransferApplockKeychain.migrateKeychainItems) //TODO: katerina check the version
Removed

2020-12-09 17:19 UTC, billypchan approved these changes

2020-12-10 22:28 UTC, KaterinaWire commented
@typfel @billypchan I moved a part related to the passcode migration to a separate PR, because this question was not yet approved by the product team.

2020-12-11 12:24 UTC, merged