[Feature] Feature configurations
wireapp/wire-ios-data-model pull request #1095
Opened 2020-12-18 16:19 UTC by KaterinaWire

## What's new in this PR?

### Issues

### Causes

### Solutions

## Dependencies

Needs releases with:

- [ ] 

## Notes

1. In PersistedDataPatches+Directory file, for `TransferApplockKeychain.migrateKeychainItems` put the new version that will be introduce with this PR.

2021-01-05 11:19 UTC, KaterinaWire commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +        if scenario.supportsUserFallback && (/*BiometricsState.biometricsChanged(in: context) || */!canEvaluatePolicy) {
This was a temporary comment because I tested it and changed the biometrics state very often.

2021-01-06 09:57 UTC, johnxnguyen requested changes

2021-01-06 09:57 UTC, johnxnguyen commented on Patches/PersistedDataPatches+Directory.swift
> +        PersistedDataPatch(version: "233.3.0", block: TransferApplockKeychain.migrateKeychainItems)
Don't forget to update this version number.

2021-01-06 10:36 UTC, marcomaddy1982 commented on Patches/TransferApplockKeychain.swift
> +        selfUser.isAppLockActive = String(data: data, encoding: .utf8) == "YES"
First of all, sorry if I missed something from the previous PRs: but why we don't use `true`/`false` instead of `YES` / `NO`?

Using `true`/`false` I guess this method will become something just

```swift
static func migrateIsAppLockActiveState(in moc: NSManagedObjectContext) {
         let selfUser = ZMUser.selfUser(in: moc)
         let data = ZMKeychain.data(forAccount: "lockApp") ?? Data()
         return String(data: data, encoding: .utf8).flatMap(Bool.init) ?? false
}
```

2021-01-06 10:40 UTC, marcomaddy1982 commented on Patches/TransferApplockKeychain.swift
> +            for id in ids {
It doesn't make much difference but to be more "swiftly"  here you could use `ids.forEach {  }`. Anyway feel free to use the approach you prefer.

2021-01-06 10:43 UTC, KaterinaWire commented on Patches/PersistedDataPatches+Directory.swift
> +        PersistedDataPatch(version: "233.3.0", block: TransferApplockKeychain.migrateKeychainItems)
The current version is `233.2.0` and it will be a major release. So, I should change to `234.0.0`, right?

2021-01-06 10:56 UTC, marcomaddy1982 commented on Source/Model/FeatureConfig/AppLock/AppLockController+Passcode.swift
> +public extension AppLockController {
I know that the `AppLockController` is a huge class but honestly I'm not a big fun of having so small category. I would just move this  `extension` in the  `AppLockController` and then use a PragmaMark for it. Anyway, this is just my opinion. Feel free to use the approach you prefer.

2021-01-06 10:58 UTC, marcomaddy1982 commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +public class BiometricsState {
Here I would move it out in a separate file.

2021-01-06 11:00 UTC, marcomaddy1982 commented on Source/Model/FeatureConfig/AppLock/AppLockController.PasscodeKeychainItem.swift
> +    struct PasscodeKeychainItem: KeychainItem {
Sorry if I missed some here too for the previous PRs: but why declaring this inside the `AppLockController`?

2021-01-06 11:04 UTC, marcomaddy1982 commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +    // MARK: - Types
Here I would separate this types and declare them outside from the `AppLockController` and remake them. As mentioned before this is just my opinion.

2021-01-06 11:31 UTC, marcomaddy1982 approved these changes

2021-01-06 11:55 UTC, johnxnguyen commented on Patches/PersistedDataPatches+Directory.swift
> +        PersistedDataPatch(version: "233.3.0", block: TransferApplockKeychain.migrateKeychainItems)
Yes

2021-01-06 13:02 UTC, KaterinaWire commented on Patches/PersistedDataPatches+Directory.swift
> +        PersistedDataPatch(version: "233.3.0", block: TransferApplockKeychain.migrateKeychainItems)
Done

2021-01-06 13:57 UTC, johnxnguyen commented on Patches/PersistedDataPatches+Directory.swift
> +        PersistedDataPatch(version: "234.0.0", block: InvalidConnectionRemoval.removeInvalid),
Did you mean to change this version too?

2021-01-06 14:27 UTC, KaterinaWire commented on Patches/PersistedDataPatches+Directory.swift
> +        PersistedDataPatch(version: "234.0.0", block: InvalidConnectionRemoval.removeInvalid),
Oh, no!
It was by accident.

2021-01-06 14:32 UTC, johnxnguyen approved these changes

2021-01-06 14:57 UTC, KaterinaWire commented
@zenkins release major

2021-01-06 14:58 UTC, merged