[Fix] Changed conditions for displaying  custom passcode screen
wireapp/wire-ios-data-model pull request #1105
Opened 2021-01-07 14:40 UTC by KaterinaWire

## What's new in this PR?

### Issues
The  custom passcode screen displays for users who should use a device passcode as a fallback.

### Solutions
Add an additional condition.
Only users who has `config.useBiometricsOrCustomPasscode == true` should use a custom passcode as a fallback.

2021-01-07 14:43 UTC, johnxnguyen reviewed
I think you forgot to replace the existing condition (line 143 onwards)

2021-01-07 14:48 UTC, KaterinaWire commented
> I think you forgot to replace the existing condition (line 143 onwards)

Fixed

2021-01-07 14:58 UTC, johnxnguyen requested changes
Please add a test asserting that:

1. custom passcode is requested if the policy can't be evaluated
2. custom passcode is requested if policy can be evaluated, but biometrics changed

2021-01-07 17:58 UTC, KaterinaWire commented
> Please add a test asserting that:
> 
> 1. custom passcode is requested if the policy can't be evaluated
> 2. custom passcode is requested if policy can be evaluated, but biometrics changed

@johnxnguyen Added tests

2021-01-08 07:50 UTC, johnxnguyen requested changes

2021-01-08 07:50 UTC, johnxnguyen commented on Tests/Source/Model/FeatureConfiguration/AppLock/AppLockControllerTest.swift
> +    }
I suppose within this method we're using a real `LAContext` to evaluate the policy. I think it would be better to mock this as to make the test more controlled and robust. You can see in https://github.com/wireapp/wire-ios/pull/4732/ that I made a `MockLAContext`, perhaps we can introduce that here.

2021-01-08 07:50 UTC, johnxnguyen commented on Tests/Source/Model/FeatureConfiguration/AppLock/AppLockControllerTest.swift
> +        let scenario = AppLockController.AuthenticationScenario.screenLock(requireBiometrics: true)
I think we should have a copy of this test when biometrics aren't required.

2021-01-08 07:50 UTC, johnxnguyen commented on Tests/Source/Model/FeatureConfiguration/AppLock/AppLockControllerTest.swift
> +        let scenario = AppLockController.AuthenticationScenario.screenLock(requireBiometrics: false)
Does setting `useBiometricsOrCustomPasscode` have any affect on the test? If I remember correctly, the evaluate method only checks the `requireBiometrics` value of the `scenario`.

Also I think you want to have `requireBiometrics` equal to `true`, since the biometric change state is related to this flag.

2021-01-08 07:50 UTC, johnxnguyen commented on Tests/Source/Model/FeatureConfiguration/AppLock/AppLockControllerTest.swift
> +        UserDefaults.standard.set(Data(), forKey: "DomainStateKey")
I suggest to mock the `biometricsChanged()` method.

2021-01-08 08:39 UTC, KaterinaWire commented on Tests/Source/Model/FeatureConfiguration/AppLock/AppLockControllerTest.swift
> +    }
Yes, it would be nice, but a real `LAContext` is created inside the `evaluateAuthentication()` method.

2021-01-08 08:40 UTC, KaterinaWire commented on Tests/Source/Model/FeatureConfiguration/AppLock/AppLockControllerTest.swift
> +        let scenario = AppLockController.AuthenticationScenario.screenLock(requireBiometrics: false)
This method mocks our bundle config. So yes, it has an affect. If `useBiometricsOrCustomPasscode` is false we use a device passcode as a fallback.

2021-01-08 08:41 UTC, KaterinaWire commented on Tests/Source/Model/FeatureConfiguration/AppLock/AppLockControllerTest.swift
> +        let scenario = AppLockController.AuthenticationScenario.screenLock(requireBiometrics: true)
This setting affects only the `scenario.policy`:
```
var policy: LAPolicy {
            switch self {
            case .screenLock(requireBiometrics: let requireBiometrics):
                return requireBiometrics ? .deviceOwnerAuthenticationWithBiometrics : .deviceOwnerAuthentication
            case .databaseLock:
                return .deviceOwnerAuthentication
            }
        }
```

I just used `requireBiometrics = true` because `deviceOwnerAuthenticationWithBiometrics` can't be evaluated by simulator and I could mock the expected behaviour.

2021-01-08 08:49 UTC, typfel requested changes

2021-01-08 08:49 UTC, typfel commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +        let biometricsChanged = BiometricsState.biometricsChanged(in: context) && config.useBiometricsOrCustomPasscode
Isn't `useBiometricsOrCustomPasscode` already part of the `AuthenticationScenario`? Seems like `AuthenticationScenario.supportsUserFallback` could take this into account. 

Then we could simplify this to:

```suggestion
        let biometricsChanged = BiometricsState.biometricsChanged(in: context)
```

2021-01-08 09:10 UTC, johnxnguyen reviewed
An idea for improving readability of tests: you could extract a lot of boilerplate code into a dedicated `assert` method which takes an `input` and an expected `output` argument. This makes it much easier to understand what is being tested and also makes it easier to set multiple tests (even all input combinations if you want). Something like:

```swift
func testEvaluateScenario() {
  assert(
    input: (scenario: .screenLock(requiresBiometrics: true), canEvaluate: true,  biometricsChanged: true),
    output: .needCustomPasscode
  )

  assert(
    input: (scenario: .screenLock(requiresBiometrics: true), canEvaluate: false,  biometricsChanged: true),
    output: .needCustomPasscode
  )
}

func assert(input: Input, output: AutnethicationResult, file: StaticString = #file, line: Uint = #line) {
 ...
}
```

2021-01-08 09:23 UTC, johnxnguyen commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +        let biometricsChanged = BiometricsState.biometricsChanged(in: context) && config.useBiometricsOrCustomPasscode
I think there may be some confusion (on my part) about what exactly `supportsUserFalback` is supposed to mean. I took it to understand that there is a secondary authentication method available. But is it suppose to mean that the fallback must be the custom passcode?

It's confusing because if you have biometrics enabled, you must also have a device pin set (which is also used as a fallback).

I'm thinking now that Jacob's suggest would work with:

```swift
var supportsUserFallback: Bool {
  switch self {
    case let .screenLock(requireBiometrics):
      return requireBiometrics
    case .databaseLock:
      return false
  }
}
```

2021-01-08 09:24 UTC, johnxnguyen commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +        let biometricsChanged = BiometricsState.biometricsChanged(in: context) && config.useBiometricsOrCustomPasscode
Probably also we should rename `supportsUserFallback` to something like `shouldFallbackToCustomPasscode`.

2021-01-08 09:30 UTC, typfel commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +        let biometricsChanged = BiometricsState.biometricsChanged(in: context) && config.useBiometricsOrCustomPasscode
>It's confusing because if you have biometrics enabled, you must also have a device pin set (which is also used as a fallback).

But we don't explicitly request the PIN code as fallback do we? It happen automatically by the OS. When EAR is enabled `supportsUserFallback` is always false but you can't still unlock your phone with the PIN if the biometric fails.

2021-01-08 09:50 UTC, johnxnguyen commented on Tests/Source/Model/FeatureConfiguration/AppLock/AppLockControllerTest.swift
> +        let scenario = AppLockController.AuthenticationScenario.screenLock(requireBiometrics: true)
It's a bit confusing though, no one would immediately understand why that is the reason `requireBiometrics` is true. I suggest to mock the `LAContext` to avoid such issues.

2021-01-08 09:53 UTC, johnxnguyen commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +        let biometricsChanged = BiometricsState.biometricsChanged(in: context) && config.useBiometricsOrCustomPasscode
Yes it's handled by the OS, but the naming `supportsUserFallback` doesn't make that so clear (leading to my confusion).

2021-01-08 09:56 UTC, johnxnguyen commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +        let biometricsChanged = BiometricsState.biometricsChanged(in: context) && config.useBiometricsOrCustomPasscode
> When EAR is enabled `supportsUserFallback` is always false but you can't still unlock your phone with the PIN if the biometric fails.

Do you mean "... but you **can** still unlock your phone with the PIN""?

If `supportsUserFallback` is false, then it means that we shouldn't allow the user to enter via a custom passcode? I'm wondering what it means if EAR is enabled and `useBiometricsOrCustomPasscode` is `true`. I guess it means that you must use biometrics only and nothing else.

2021-01-08 10:03 UTC, KaterinaWire commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +        let biometricsChanged = BiometricsState.biometricsChanged(in: context) && config.useBiometricsOrCustomPasscode
`useBiometricsOrCustomPasscode` doesn't affect EAR. 
```
var policy: LAPolicy {
            switch self {
            case .screenLock(requireBiometrics: let requireBiometrics):
                return requireBiometrics ? .deviceOwnerAuthenticationWithBiometrics : .deviceOwnerAuthentication
            case .databaseLock:
                return .deviceOwnerAuthentication
            }
        }
```

2021-01-11 06:35 UTC, KaterinaWire commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +//    private weak var weakLAContext: LAContextProtocol? = nil
@typfel I'm not sure if we still need to persist `weakLAContext`.

2021-01-11 06:38 UTC, KaterinaWire commented on Tests/Source/Model/FeatureConfiguration/AppLock/AppLockControllerTest.swift
> +    }
I added `MockLAContext` and replaced this test

2021-01-11 06:39 UTC, KaterinaWire commented on Tests/Source/Model/FeatureConfiguration/AppLock/AppLockControllerTest.swift
> +        let scenario = AppLockController.AuthenticationScenario.screenLock(requireBiometrics: true)
Test was replaced

2021-01-11 06:39 UTC, KaterinaWire commented on Tests/Source/Model/FeatureConfiguration/AppLock/AppLockControllerTest.swift
> +        let scenario = AppLockController.AuthenticationScenario.screenLock(requireBiometrics: false)
Test was replaced

2021-01-11 06:40 UTC, KaterinaWire commented on Tests/Source/Model/FeatureConfiguration/AppLock/AppLockControllerTest.swift
> +        UserDefaults.standard.set(Data(), forKey: "DomainStateKey")
`biometricsChanged()` is mocked and test was replaced

2021-01-11 06:41 UTC, KaterinaWire commented
> An idea for improving readability of tests: you could extract a lot of boilerplate code into a dedicated `assert` method which takes an `input` and an expected `output` argument. This makes it much easier to understand what is being tested and also makes it easier to set multiple tests (even all input combinations if you want). Something like:
> 
> ```swift
> func testEvaluateScenario() {
>   assert(
>     input: (scenario: .screenLock(requiresBiometrics: true), canEvaluate: true,  biometricsChanged: true),
>     output: .needCustomPasscode
>   )
> 
>   assert(
>     input: (scenario: .screenLock(requiresBiometrics: true), canEvaluate: false,  biometricsChanged: true),
>     output: .needCustomPasscode
>   )
> }
> 
> func assert(input: Input, output: AutnethicationResult, file: StaticString = #file, line: Uint = #line) {
>  ...
> }
> ```

@johnxnguyen Implemented

2021-01-11 06:46 UTC, KaterinaWire commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +        let biometricsChanged = BiometricsState.biometricsChanged(in: context) && config.useBiometricsOrCustomPasscode
@typfel @johnxnguyen I replaced `var supportsUserFallback: Bool ` with `var supportedUserFallback: UserFallback`
And 
```
enum UserFallback {
        /// User is allowed to use only a custom passcode as a fallback
        case customPasscode
        /// User is allowed to use only a device passcode as a fallback
        case devicePasscode
        /// User is allowed to use any fallback
        case all
    }
```
Because we have different use cases for `UserFallback`.

2021-01-11 06:50 UTC, typfel commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +//    private weak var weakLAContext: LAContextProtocol? = nil
If nothing references it we don't need it and since it was private this is a safe assumption.

2021-01-11 07:01 UTC, typfel commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +                                       with callback: @escaping (AuthenticationResult, LAContextProtocol) -> Void) {
Just be aware that this is now a breaking change. The context in the closure is calling `unlockDatabase(with context: LAContext)` via the UI project. That path also needs to be updated to use `LAContextProtocol`

2021-01-11 07:14 UTC, typfel commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +        let shouldUseCustomPasscodeAsFallback = biometricsState.biometricsChanged(in: context) && (scenario.supportedUserFallback == .customPasscode)
IMO this is easier to read if we rename `shouldUseCustomPasscodeAsFallback` to `biometricsChanged `.

```suggestion
        let biometricsChanged = biometricsState.biometricsChanged(in: context) && (scenario.supportedUserFallback == .customPasscode)
```

2021-01-11 07:47 UTC, johnxnguyen commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +    }
Why do we need this? The ui for presenting the entering the device passcode isn't something managed by us. Indeed I noticed that we never check in the evaluate method if `supportedUserFallback == .devicePasscode`.

2021-01-11 07:47 UTC, johnxnguyen commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +                return .devicePasscode
As far as I understand, the user fallback is only referring to a custom passcode as a secondary way to unlock the app. I believe the only scenario in which we can have such a fallback is the screen lock with biometrics required. We don't support using a device pin and a custom passcode as a fallback. And if we don't have even a device pin, we wouldn't ever use the `evaluate` method because custom passcode verification happens outside of the `AppLockController`.

2021-01-11 07:47 UTC, johnxnguyen commented on Source/Model/FeatureConfig/AppLock/BiometricsState.swift
> +   func biometricsChanged(in context: LAContextProtocol) -> Bool
Is there a need to pass in `LAContextProtocol` or can we simply pass `LAContext`? If we're mocking this method, we don't need to use the argument at all and therefore we wouldn't need to rely on the `evaluatedPolicyDomainState`. This means we could remove that requirement from `LAContextProtocol` to keep it simpler.

2021-01-11 07:47 UTC, johnxnguyen commented on Tests/Source/Model/FeatureConfiguration/AppLock/AppLockControllerTest.swift
> +        _ = sut.biometricsState.biometricsChanged(in: context)
By setting `Data()` as both the value in user defaults and `context.evaluatedPolicyDomainState`, you won't be able to assert that the persist method does anything; it could not work and the assertion that below would still be true. Better to store some other data in the context to see if that is saved in the user defaults.

Also, it would be good to clean up the value in user defaults at the end of the test.

2021-01-11 10:10 UTC, johnxnguyen commented on Tests/Source/Model/FeatureConfiguration/AppLock/AppLockControllerTest.swift
> -        )
We should probably assert that the output is something like `.denied`.

2021-01-11 10:10 UTC, johnxnguyen commented on Tests/Source/Model/FeatureConfiguration/AppLock/AppLockControllerTest.swift
> +        XCTAssertTrue(sut.biometricsState.biometricsChanged(in: context))
You should also clean up the user defaults value for this test too.

2021-01-11 10:10 UTC, johnxnguyen commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +        var usesCustomPasscodeAsUserFallback: Bool {
Suggestion: `usesCustomPasscodeAsFallback`

2021-01-11 10:22 UTC, KaterinaWire commented on Source/Model/FeatureConfig/AppLock/AppLockController.swift
> +        var usesCustomPasscodeAsUserFallback: Bool {
Done

2021-01-11 10:22 UTC, KaterinaWire commented on Tests/Source/Model/FeatureConfiguration/AppLock/AppLockControllerTest.swift
> +        XCTAssertTrue(sut.biometricsState.biometricsChanged(in: context))
Done

2021-01-11 10:27 UTC, typfel approved these changes

2021-01-11 10:51 UTC, johnxnguyen approved these changes

2021-01-11 11:06 UTC, KaterinaWire commented on Tests/Source/Model/FeatureConfiguration/AppLock/AppLockControllerTest.swift
> -        )
The output should be `.unavailable`, but the test fails. 
```
if canEvaluatePolicy {
...
} else {
            callback(.unavailable, context)
            zmLog.error("Local authentication error: \(String(describing: error?.localizedDescription))")
}
```
It fails because of `zmLog.error(...)` . Do you know why it happened?
Logs says:
`-[WireDataModelTests.AppLockControllerTest testEvaluateScenario] : failed - Unexpected log error:`

2021-01-11 12:15 UTC, KaterinaWire commented on Tests/Source/Model/FeatureConfiguration/AppLock/AppLockControllerTest.swift
> -        )
As I understood, `evaluateAuthentication(...)` method throws the error (`zmLog.error("Local authentication error: \(String(describing: error?.localizedDescription))")`), which I can't catch from the test.

2021-01-11 19:24 UTC, typfel commented on Tests/Source/Model/FeatureConfiguration/AppLock/AppLockControllerTest.swift
> -        )
Tests will fail if errors are logged while they execute. If the errors are expected the error producing methods need to be wrapped inside a `performIgnoringZMLogError {}` block.

2021-01-12 08:43 UTC, KaterinaWire commented on Tests/Source/Model/FeatureConfiguration/AppLock/AppLockControllerTest.swift
> -        )
Thanks!

2021-01-12 11:19 UTC, KaterinaWire commented
@zenkins release major

2021-01-12 11:20 UTC, merged