Fix: change UserType properties with ZMConversation parameter to optional
wireapp/wire-ios-data-model pull request #1114
Opened 2021-01-13 16:12 UTC by billypchan

## What's new in this PR?

change `UserType` properties with `ZMConversation` parameter to optional to allow mocking `UserType` without creating a `ZMConversation` instance.

Add `hasTeam` property to `UserType`

2021-01-14 09:53 UTC, johnxnguyen reviewed
Could you elaborate what problem this is solving? I don't quite see how making the arguments optional makes it easier to mock.

2021-01-15 07:59 UTC, johnxnguyen commented
@billypchan please see the comment on my first review.

2021-01-15 09:49 UTC, johnxnguyen reviewed
I'm concerned that we are making the `UserType` more confusing by making the arguments optional. I believe we should strive to maintain a clear and unambiguous API and that we shouldn't sacrifice this testability.

But that doesn't mean that we shouldn't improve testability, I would just suggest we consider an alternative solution, such as using a `ConversationType` (or perhaps a less confusing name) just like we do for `UserType`. Do you think that be a feasible approach?

2021-01-15 10:36 UTC, billypchan commented
@johnxnguyen I agree that `ConversationType` would be our final target, and I am creating a partially done protocol here:

https://github.com/wireapp/wire-ios/pull/4833/files#diff-be275f7def39aa5bedd90ad675663693f8fc3a4c5c07ca73236f2cc0d615e775

The problem currently is there are a lot of methods of `ZMConversation` having parameter type `ZMUser`, we have to change them to `UserType` before making everything in pure abstract interfaces.
I would suggest agree on this PR first, to solve the issue in https://github.com/wireapp/wire-ios/pull/4833. After we collected what we need in `ConversationType`, we can move it back to this framework and update these methods again.

2021-01-15 10:51 UTC, johnxnguyen commented
> The problem currently is there are a lot of methods of ZMConversation having parameter type ZMUser, we have to change them to UserType before making everything in pure abstract interfaces.

But do you need to make everything pure abstract interfaces for all of `ZMConversation`. Looking at the `UserType` methods that are affected here, it appears that you only use the properties `isSelfAnActiveMember` and `conversationType`.

2021-01-18 06:54 UTC, typfel commented
>But do you need to make everything pure abstract interfaces for all of ZMConversation. Looking at the UserType methods that are affected here, it appears that you only use the properties isSelfAnActiveMember and conversationType.

So this sounds feasible! I would rather have that we have an incomplete `ConversationType` protocol than that we start making argument optional which shouldn't be optional.

2021-01-18 06:55 UTC, typfel requested changes
Use `ConversationType` protocol instead of making arguments optional.

2021-01-18 12:05 UTC, johnxnguyen requested changes

2021-01-18 12:05 UTC, johnxnguyen commented on Source/Model/Conversation/ConversationType.swift
> +    var conversationType: ZMConversationType { get }
Admittedly it's kind of confusing to have `ConversationType` mean "some conversation like object" and also a `ZMConversationType` mean "the type of a conversation".

I've seen the prefix "Like" to indicate that an object is "like" some abstract version of it. For example:

```swift
protocol ConversationLike {
  var conversationType: ZMConversationType { get }
  var isSelfAnActiveMember: Bool { get }
}

extension ZMConversation: ConversationLike { }
```

2021-01-18 12:05 UTC, johnxnguyen commented on Source/Model/User/ZMUser+Permissions.swift
> +        guard let conversation = conversation as? ZMConversation,
Why not pass these down without casting? It would save the duplication and it also means you don't have to assume what the concrete type is. If I remember correctly, when accessing a role you need to check that it equals the `ZMConversation` instance, but here you could just use referential equality instead of casting.

2021-01-18 13:02 UTC, billypchan commented on Source/Model/User/ZMUser+Permissions.swift
> +        guard let conversation = conversation as? ZMConversation,
Change `hasRoleWithAction` to save a casting.

2021-01-18 13:06 UTC, billypchan commented on Source/Model/Conversation/ConversationType.swift
> +    var conversationType: ZMConversationType { get }
renamed for your suggestion.

2021-01-18 13:26 UTC, johnxnguyen commented on Source/Model/User/ZMUser+Permissions.swift
> +                && true == (conversation as? ZMConversation)?.localParticipants.contains(self)
Is there any way we can avoid this cast? Can we add one more requirement to `ConversationLike` to cover this, such as `isParticipant(user: UserType) -> Bool` ?

2021-01-18 13:43 UTC, billypchan commented on Source/Model/User/ZMUser+Permissions.swift
> +                && true == (conversation as? ZMConversation)?.localParticipants.contains(self)
added the new method for your suggestion. Actually, this checker is call in several places in the UI project and we can replace them.

2021-01-18 13:46 UTC, johnxnguyen commented on Source/Model/Conversation/ConversationLike.swift
> +        guard let user = user as? ZMUser else { return false }
Do we ever check if a search user is in the local participants?

2021-01-18 13:49 UTC, billypchan commented on Source/Model/Conversation/ConversationLike.swift
> +        guard let user = user as? ZMUser else { return false }
`localParticapants` should never contians search user since it has the type `Set<ZMUser>`

2021-01-18 14:12 UTC, johnxnguyen commented on Source/Model/Conversation/ConversationLike.swift
> +        guard let user = user as? ZMUser else { return false }
Yeah you're right, was just wondering.

2021-01-18 14:14 UTC, johnxnguyen approved these changes

2021-01-20 06:40 UTC, typfel approved these changes

2021-01-20 08:56 UTC, billypchan commented
@zenkins release major

2021-01-20 08:57 UTC, merged