Move Conversation properties to ConversationLike
wireapp/wire-ios-data-model pull request #1126
Opened 2021-01-26 19:26 UTC by billypchan

## What's new in this PR?

Move Conversation form UI project protocol to `ConversationLike`. Put the Swift only property in extension to protocol `SwiftConversationLike` and create a new alias `Conversation` to combine them.

2021-01-27 10:19 UTC, billypchan commented on Source/Model/Conversation/ConversationLike.swift
> +public typealias Conversation = ConversationLike & SwiftConversationLike
I suggest use simply `Conversation` as the protocol name. Since we have name tradition e.g. `ZMConversationMessage` to Message managed object.

2021-01-28 07:24 UTC, johnxnguyen approved these changes
It would be nice to document each protocol requirement.

2021-01-28 12:04 UTC, marcomaddy1982 approved these changes

2021-01-28 15:51 UTC, typfel requested changes

2021-01-28 15:51 UTC, typfel commented on Source/Model/Conversation/ConversationLike.swift
> +    var team: Team? { get }
Could we use `TeamType` here?

2021-01-28 15:51 UTC, typfel commented on Source/Model/Conversation/ConversationLike.swift
>  @objc
Question: Why do we need to expose `ConversationLike` to objective-c now that the whole UI project is in Swift?

2021-01-28 16:49 UTC, billypchan commented on Source/Model/Conversation/ConversationLike.swift
> +    var team: Team? { get }
replaced with `TeamType`

2021-01-28 16:53 UTC, billypchan commented on Source/Model/Conversation/ConversationLike.swift
>  @objc
`UserType` has to be @objc and has several @objc methods (e.g. `@objc(canAddUserToConversation:)`) and so we still need a @objc `ConversationLike`.

`SwiftConversationLike` is for swift `ZMConversation`'s swift extensions.

2021-01-28 17:09 UTC, typfel commented on Source/Model/Conversation/ConversationLike.swift
>  @objc
Ok, we should review those `@objc` annotation at some point and see if we can remove them.

2021-01-28 17:16 UTC, merged