Add quoteMessage to ZMTextMessageData
wireapp/wire-ios-data-model pull request #1128
Opened 2021-01-28 10:01 UTC by billypchan

## What's new in this PR?

Add `quoteMessage` with type `ZMConversationMessage` to `ZMTextMessageData` to allow mocking `quota` with creating a `ZMMessage` managed object.

2021-01-28 12:05 UTC, marcomaddy1982 approved these changes

2021-01-28 15:57 UTC, typfel requested changes

2021-01-28 15:57 UTC, typfel commented on Source/Public/ZMMessage.h
>  @property (nonatomic, readonly, nullable) ZMMessage *quote;
Can't we remove this? Seems like most references to `quote` in the UI is anyway expecting a `ZMConversationMessage`. 

And if we can remove it you could keep the `quote` name.

2021-01-28 17:02 UTC, billypchan commented on Source/Public/ZMMessage.h
>  @property (nonatomic, readonly, nullable) ZMMessage *quote;
We need to reserve `ZMMessage *quote` since `ZMClientMessage` conforms `ZMTextMessageData` and its has ` @NSManaged public var quote: ZMMessage?`

2021-01-28 17:04 UTC, typfel commented on Source/Public/ZMMessage.h
>  @property (nonatomic, readonly, nullable) ZMMessage *quote;
Ah I see but we could still remove `ZMMessage *quote` from protocol?

2021-01-28 19:21 UTC, billypchan commented on Source/Public/ZMMessage.h
>  @property (nonatomic, readonly, nullable) ZMMessage *quote;
It is removed, thanks!

2021-01-29 06:25 UTC, typfel approved these changes

2021-01-29 07:55 UTC, merged