[FIX]: Handle gracefully when device runs out of disk space
wireapp/wire-ios-data-model pull request #1144
Opened 2021-03-01 10:39 UTC by marcomaddy1982

## What's new in this PR?

### Issues

See the [issue](https://wearezeta.atlassian.net/browse/SQCORE-429)

When there was a problem to load the database in case we run out of disk space (or for any other error), the database was  dropped. This means that the user was losing all the previous conversation

### Solutions

Now a screen similar to the `blacklisted` or `jailbroken` is shown but with a different message

2021-03-03 06:37 UTC, typfel reviewed
Did you investigate if it's possible to add test for checking that the callback gets called when the database can't be loaded?

2021-03-03 09:18 UTC, marcomaddy1982 commented
> Did you investigate if it's possibility to add test for checking that the callback gets called when the database can't be loaded?

Yes I did. 

@typfel Anyway there are some ongoing discussions with the design team so stuffs could changes in the next day.

2021-03-04 19:56 UTC, typfel commented
> > Did you investigate if it's possibility to add test for checking that the callback gets called when the database can't be loaded?
> 
> Yes I did.

And what was the result? Not possible at all or just a lot of work?

2021-03-05 07:17 UTC, marcomaddy1982 commented
> > > Did you investigate if it's possibility to add test for checking that the callback gets called when the database can't be loaded?
> > 
> > 
> > Yes I did.
> 
> And what was the result? Not possible at all or just a lot of work?

I didn't find any way to test it.

2021-03-05 13:37 UTC, typfel approved these changes

2021-03-05 14:48 UTC, KaterinaWire approved these changes

2021-03-11 10:12 UTC, typfel commented on Source/ManagedObjectContext/PersistentStorageInitialization.swift
> +                startedMigrationCallback: nil,
Why is this nil now?

2021-03-11 10:21 UTC, typfel requested changes

2021-03-11 10:21 UTC, typfel commented on Source/ManagedObjectContext/PersistentStorageInitialization.swift
> +                startedMigrationCallback: nil,
Why is this nil now?

2021-03-11 10:21 UTC, typfel commented on Source/ManagedObjectContext/PersistentStorageInitialization.swift
> +                accountIdentifier: nil,
Why is this nil now?

2021-03-11 10:21 UTC, typfel commented on Source/ManagedObjectContext/PersistentStorageInitialization.swift
> +                return
Returning without calling the completion handler is something which can lead to bugs for the user of this API since it's often not something you consider when using such an API.

Maybe it's better if we bubble any error all the way up to SE by marking this method as throwing instead of having the `databaseLoadingFailureCallBack`?

2021-03-11 10:21 UTC, typfel commented on Source/ManagedObjectContext/NSPersistentStoreCoordinator+Wire.swift
>          let addStore = { _ = try self.addPersistentStore(ofType: NSSQLiteStoreType, configurationName: nil, at: url, options: options) }
No need for this closure now that only use it once.

2021-03-11 10:21 UTC, typfel commented on Source/ManagedObjectContext/NSPersistentStoreCoordinator+Wire.swift
> +            return true
Returning true / false to signal success or failure is often confusing. I'd suggest letting the error bubble up instead.

2021-03-11 10:24 UTC, marcomaddy1982 commented on Source/ManagedObjectContext/PersistentStorageInitialization.swift
> +                accountIdentifier: nil,
ops my bad, I don't know what's happened!! Same next comment!!!

2021-03-11 11:09 UTC, marcomaddy1982 commented on Source/ManagedObjectContext/PersistentStorageInitialization.swift
> +                return
I understand you suggestion. Anyway I have a question: So you mean also that I should not have the `optional` `convenience init?(` on the `NSPersistentStoreCoordinator` and return in any case the persistentStoreCoordinator?

The reason why I adopted that approach is because when the database is deleted and the  `completionHandler(persistentStoreCoordinator)` is executed also a crash is happening.

2021-03-11 11:27 UTC, typfel commented on Source/ManagedObjectContext/PersistentStorageInitialization.swift
> +                return
Or maybe this is not working to due to it being asynchronous? I haven't checked it, was just an idea.

2021-03-11 11:35 UTC, marcomaddy1982 commented on Source/ManagedObjectContext/PersistentStorageInitialization.swift
> +                return
> I'm suggesting to make the init() throwing instead of optional (and every method above). The catching of the error would then happen SE.

Ok this is a clear. Thanks. And if I understood correctly in the `catch`  together with the `databaseLoadingFailureCallBack()` I should execute the `completionHandler(persistentStoreCoordinator)` which before leads to have a crash.

> Or maybe this is not working to due to it being asynchronous? I haven't checked it, was just an idea.

This is a good point.

2021-03-11 11:42 UTC, typfel commented on Source/ManagedObjectContext/PersistentStorageInitialization.swift
> +                return
Hmm but the only reason why this is asynchronous is due to it being wrapped inside `executeWhenFileIsAccessible`.  But maybe we can remove it now after https://github.com/wireapp/wire-ios/pull/4794 which doesn't even create the SessionManaged until the file system is accessible.

2021-03-11 11:44 UTC, marcomaddy1982 commented on Source/ManagedObjectContext/PersistentStorageInitialization.swift
> +                return
Ok I can have a look.

2021-03-16 10:20 UTC, marcomaddy1982 commented on Source/ManagedObjectContext/NSPersistentStoreCoordinator+Wire.swift
> +            return true
Done

2021-03-17 11:06 UTC, typfel requested changes

2021-03-17 11:06 UTC, typfel commented on Source/ManagedObjectContext/PersistentStorageInitialization.swift
> +            completionHandler(persistentStoreCoordinator)
Since this method is synchronous now you can return `persistentStoreCoordinator` instead using a completionHandler. You would then also need to cascade the `throws` further up.

2021-03-17 13:13 UTC, marcomaddy1982 commented on Source/ManagedObjectContext/PersistentStorageInitialization.swift
> +            completionHandler(persistentStoreCoordinator)
All done!!!

2021-03-17 23:23 UTC, KaterinaWire approved these changes

2021-03-18 13:14 UTC, typfel approved these changes

2021-03-18 13:20 UTC, marcomaddy1982 commented
@zenkins release major

2021-03-18 13:21 UTC, merged