Add properties to ConversationLike
wireapp/wire-ios-data-model pull request #1147
Opened 2021-03-05 13:48 UTC by billypchan

## What's new in this PR?

Add more properties to `ConversationLike` to allow the UI project to mock those properties

2021-03-17 11:10 UTC, typfel requested changes

2021-03-17 11:10 UTC, typfel commented on Source/Model/Conversation/ConversationLike.swift
> +    var lastMessage: ZMMessage? { get }
We shouldn't expose `ZMMessage` to the UI, we should return a `ZMConversationMessage`

2021-04-01 15:15 UTC, typfel approved these changes

2021-04-06 11:26 UTC, KaterinaWire approved these changes

2021-04-06 11:35 UTC, billypchan commented
@zenkins release major

2021-04-06 11:36 UTC, merged