[Feature] Add the property of participants removed reason to the system message
wireapp/wire-ios-data-model pull request #1158
Opened 2021-05-17 07:28 UTC by KaterinaWire

## What's new in this PR?

If users don't want/support LH, they will be kicked from group conversations, and the event `"conversation.member-leave"` data will contain an extra field `”reason”: “legalhold-policy-conflict”`. 
Since the UI project should display different text, depending on this reason, we should store the reason in the system message property.

Needs releases with:

- [ wireapp/wire-ios-transport/pull/182 ]

## Notes
https://wearezeta.atlassian.net/browse/SQSERVICES-442

2021-05-17 12:01 UTC, johnxnguyen approved these changes
I was going to comment that we should avoid to have such specific properties for `ZMSystemMessage` and to avoid having to create a new property in the database... but then I realized that is necessary due to how we store system messages in the database 😀

2021-05-17 13:08 UTC, KaterinaWire commented on Tests/Source/Model/Messages/ZMMessageTests+SystemMessages.swift
> +        var result: ZMSystemMessage! = nil
It was by mistake. 
Fixed

2021-05-17 13:08 UTC, KaterinaWire commented on Tests/Source/Model/Messages/ZMMessageTests+SystemMessages.swift
> +        }
Fixed

2021-05-18 09:29 UTC, typfel requested changes

2021-05-18 09:29 UTC, typfel commented on Source/Model/Message/ZMSystemMessage+ParticipantsRemovedReason.swift
> +    @objc public var participantsRemovedReason: ParticipantsRemovedReason {
This is coupling the ZMSystemMessage entity with a transport data structure. I think we should create a new enum in data model. This would support the goal of removing wire-ios-transport as a dependency in wire-ios-data-model.

2021-05-20 06:24 UTC, KaterinaWire commented on Source/Model/Message/ZMSystemMessage+ParticipantsRemovedReason.swift
> +    @objc public var participantsRemovedReason: ParticipantsRemovedReason {
I moved this enum from wire-ios-transport to wire-ios-data-model. I implemented it on Objective C because I need to use it in the header file and it's not possible to import bridge file to the header file and use Swift enum.

2021-05-21 05:55 UTC, typfel approved these changes

2021-05-23 23:49 UTC, merged