Fix: UTType init returns nil on M1 Mac
wireapp/wire-ios-data-model pull request #1176
Opened 2021-07-09 16:44 UTC by billypchan

## What's new in this PR?

### Issues

When running test on M1 Mac iOS simulator, `UTType(mimeType: )` always return nil and cause `hasRasterImage` always false

### Causes

Unknown

### Solutions

As a workaround, check `mimeType` is SVG to return it is a raster image or not.

related PR:
https://github.com/wireapp/wire-ios-images/pull/43

2021-07-13 08:53 UTC, David-Henner approved these changes

2021-07-13 21:24 UTC, billypchan commented
I checked that this issue is related to a bug of arm64 simulator. But I would keep this temporary fix til arm64 simulator frameworks are ready.

2021-07-14 08:43 UTC, typfel commented
@billypchan I don't so this issue wasn't resolved by https://github.com/wireapp/wire-ios-images/pull/43 ?

2021-07-14 08:45 UTC, billypchan commented
@typfel that PR was solved the tests failures on `wire-ios-images` and this PR fixes the new failure found on `wire-ios`.

2021-07-14 09:04 UTC, typfel requested changes

2021-07-14 09:04 UTC, typfel commented on Source/Model/Message/RasterImages+Protobuf.swift
> +        #if targetEnvironment(simulator)
So the root cause issue for this problem is missing arm64 simulator support?

Then let's add a
// FUTUREWORK remove once arm64 simulator support have been added (<link to JIRA ticket>)

2021-07-14 09:36 UTC, billypchan commented on Source/Model/Message/RasterImages+Protobuf.swift
> +        #if targetEnvironment(simulator)
```suggestion
        // FUTUREWORK remove once arm64 simulator support have been added JIRA ticket: SQPIT-583
        #if targetEnvironment(simulator)
```

2021-07-14 10:00 UTC, typfel approved these changes

2021-07-14 10:15 UTC, merged