[Feature] Add actions for joining conversation with key and code
wireapp/wire-ios-data-model pull request #1267
Opened 2021-11-09 09:06 UTC by sb88k

## What's new in this PR?

Refactor conversation join logic into EntityAction and EntityActionHandler pattern

2021-11-09 10:04 UTC, typfel requested changes

2021-11-10 13:30 UTC, sb88k commented on Source/Model/Conversation/ZMConversation+FetchIDAndName.swift
> +    public static func fetchIDAndName(context: NotificationContext,
Done

2021-11-10 13:30 UTC, sb88k commented on Source/Model/Conversation/ZMConversation+Join.swift
> +public class JoinAction: EntityAction {
Done

2021-11-10 13:31 UTC, sb88k commented on Source/Model/Conversation/ZMConversation+Join.swift
> +                            completion: @escaping JoinAction.ResultHandler) {
Done

2021-11-15 21:22 UTC, KaterinaWire approved these changes

2022-01-11 10:02 UTC, typfel approved these changes

2023-09-25 19:51 UTC, closed without merging