[Feature] check domain when checking if users are on the same team
wireapp/wire-ios-data-model pull request #1269
Opened 2021-11-09 16:54 UTC by David-Henner

## What's new in this PR?

https://wearezeta.atlassian.net/browse/FS-35

Consider the domain when checking if users are on the same team. 

Provided that `canAccessCompanyInformation` is used whenever we're checking if users are on the same team, checking that domains are equal ensures we won't mistake users as team members when team ids are the same but domains differ (in federation context).

2021-11-12 11:43 UTC, typfel requested changes

2021-11-12 11:43 UTC, typfel commented on Source/Model/User/ZMUser+Permissions.swift
> +        return selfUserTeamID == otherUserTeamID && domain == otherUser.domain
Since we can't be guaranteed that domain is always set for all users I think this will fail in some cases. 

For example when the `selfUser` has a domain but it's `nil` for the `otherUser`. In this case we would incorrectly return false.

A safer approach would be to change the statement to:
```
selfUserTeamID == otherUserTeamID && !otherUser.isFederated
```

2021-11-17 09:49 UTC, KaterinaWire approved these changes

2021-11-19 09:55 UTC, typfel approved these changes

2021-11-25 14:32 UTC, merged