[Feature] Mentions in federated conversation
wireapp/wire-ios-data-model pull request #1274
Opened 2021-11-12 17:00 UTC by sb88k

## What's new in this PR?

Mention feature in federated conversation

### Attachments
<img width="745" alt="Screenshot 2021-11-12 at 17 53 41" src="https://user-images.githubusercontent.com/13096974/141505111-16ee0823-2916-4c71-948a-2b63cd8bf27a.png">

<img width="745" alt="Screenshot 2021-11-12 at 17 53 41" src="https://user-images.githubusercontent.com/13096974/141505171-cef6c85b-8f0e-4b22-91c1-eca995ffdf53.png">

2021-11-15 09:15 UTC, typfel requested changes

2021-11-15 09:15 UTC, typfel commented on Source/Utilis/Protos/GenericMessage+Helper.swift
> +            if user.isFederated,
We want to include the domain for all users if available so I'd suggest to remove `user.isFederated`

2021-11-15 10:30 UTC, typfel approved these changes

2021-11-16 15:25 UTC, David-Henner approved these changes

2021-11-25 14:27 UTC, merged