[Feature] Broadcast availability to same backend users
wireapp/wire-ios-data-model pull request #1275
Opened 2021-11-15 16:55 UTC by sb88k

## What's new in this PR?

Removing recipients from other backend when broadcasting availability change

2021-11-16 09:09 UTC, typfel requested changes

2021-11-16 09:09 UTC, typfel commented on Source/Model/User/ZMUser+Availability.swift
> +        recipients = recipients.filter { $0.domain == domain }
```suggestion
        recipients = recipients.filter { !$0.isFederated }
```

2021-11-16 09:10 UTC, typfel commented on Source/Model/User/ZMUser+Availability.swift
> +        recipients = recipients.filter { $0.domain == domain }
This is shorter and handles edge cases when the domain is `nil` on the user.

2021-11-25 14:34 UTC, typfel approved these changes

2021-11-25 14:49 UTC, David-Henner approved these changes

2021-11-25 15:06 UTC, sb88k commented
release minor

2021-11-25 15:35 UTC, sb88k commented
release minor

2021-11-25 15:36 UTC, merged