test(client-session): Client session identifier migration #FS-48
wireapp/wire-ios-data-model pull request #1286
Opened 2021-11-17 17:05 UTC by sb88k

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Need to migrate the client session identifier to contain the domain.
The logic is already written and this PR is for adding unit tests.

### Testing

Testing if v2 session identifier is correctly migrated into the session directory.
Tried to write test for v1 -> v2 migration function, but it was not possible without making change in some of the production code.

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2021-11-18 09:07 UTC, typfel requested changes

2021-11-18 09:07 UTC, typfel commented on Tests/Source/Model/UserClient/UserClientTests.swift
> +                XCTAssertTrue(sessionsDirectory.hasSession(for: v2SessionIdentifier))
Shouldn't we check that it has a session for a v3 identifier
```
XCTAssertTrue(sessionsDirectory.hasSession(for: v3SessionIdentifier))
```

2021-11-18 10:46 UTC, sb88k commented on Tests/Source/Model/UserClient/UserClientTests.swift
> +                XCTAssertTrue(sessionsDirectory.hasSession(for: v2SessionIdentifier))
I wrote two test cases.
One for checking if the migration is happening when possible, and the other one for checking if it is NOT happening.

This test case is for checking if the migration is NOT happening, because the domain is missing.
so, I am checking if the identifier exists after calling the migration function.

2021-11-18 10:47 UTC, sb88k commented on Tests/Source/Model/UserClient/UserClientTests.swift
> +                XCTAssertTrue(sessionsDirectory.hasSession(for: v2SessionIdentifier))
The other test case is checking if v3 exists and v2 doesn't after calling the migration function.

2021-11-18 10:50 UTC, typfel commented on Tests/Source/Model/UserClient/UserClientTests.swift
> +                XCTAssertTrue(sessionsDirectory.hasSession(for: v2SessionIdentifier))
🤦

2021-11-18 10:50 UTC, typfel approved these changes

2021-11-24 17:16 UTC, David-Henner approved these changes

2021-11-25 14:45 UTC, merged