feat: consider domain when checking conversation team - FS-108
wireapp/wire-ios-data-model pull request #1288
Opened 2021-11-18 17:45 UTC by David-Henner

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._

### Causes (Optional)

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2021-11-18 17:51 UTC, David-Henner commented on Source/Model/Conversation/ZMConversation+Participants.swift
> +            needsToDownloadRoles = true
this will be executed if the conversation doesn't belong to the same team or if the conversation belongs to another domain. If it shouldn't be executed when the conversation is federated, then we need to change the guard to return early in such cases.

2021-11-24 13:58 UTC, typfel requested changes

2021-11-24 13:58 UTC, typfel commented on Source/Model/User/ZMUser+Permissions.swift
> +            if conversation.creator == self || conversation.isFederating(with: self) {
So here we are saying that self user is not a guest in a conversation if the conversation belongs do a different domain.

I think that's wrong we should consider the self user to be a guest.

2021-11-24 13:58 UTC, typfel commented on Source/Model/User/ZMUser+Permissions.swift
>                  return conversation.teamRemoteIdentifier != team.remoteIdentifier
I think here we need a something like:
```
return conversation.teamRemoteIdentifier != team.remoteIdentifier || conversation.isFederating(with: self))
```

2021-11-24 14:17 UTC, David-Henner commented on Source/Model/User/ZMUser+Permissions.swift
> +            if conversation.creator == self || conversation.isFederating(with: self) {
I see your point, my bad. I think I applied the "federated users are never guests" rule to the conversation, as in "users in federated conversations are never guests"

2021-11-24 14:18 UTC, David-Henner commented on Source/Model/User/ZMUser+Permissions.swift
>                  return conversation.teamRemoteIdentifier != team.remoteIdentifier
Yes, seems right.

2021-11-24 14:37 UTC, typfel commented on Source/Model/Conversation/ZMConversation+Participants.swift
> +            needsToDownloadRoles = true
Yes makes sense. Federation conversation are by design never team conversations from the perspective of the self user since teams can't contain federated users.

2021-11-24 17:05 UTC, typfel approved these changes

2021-11-25 13:53 UTC, sb88k approved these changes

2021-11-25 14:33 UTC, merged