fix: update merge sell action to bump version.xcconfig SQPIT-773
wireapp/wire-ios-data-model pull request #1290
Opened 2021-11-19 11:14 UTC by billypchan

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Recent framework release does not update `version.xcconfig`

### Causes (Optional)

It was done by Jenkins script, after we use `mergePR` action this feature is not included

### Solutions

Add this feature to mergePR action.
This action is tested in https://github.com/wireapp/wire-ios-canvas/pull/33
Add @agisilaos and @sb88k to admin list so that they can use this spell

2021-11-19 11:21 UTC, johnxnguyen approved these changes

2021-11-22 09:07 UTC, typfel requested changes
Let's make the commit message adhere to semantic commit message: https://sparkbox.com/foundry/semantic_commit_messages

2021-11-22 09:07 UTC, typfel commented on .github/workflows/mergePR.yml
> +          git commit -m"update version.xcconfig for '${{ steps.tag_version.outputs.new_tag }}'" || true
```suggestion
          git commit -m"chore: Update version.xcconfig for '${{ steps.tag_version.outputs.new_tag }}'" || true
```

2021-11-22 09:10 UTC, typfel commented
So are currently copying this script to all repos? Would it make sense to move it to the global `.github` folder? https://github.com/wireapp/.github ?

2021-11-22 09:41 UTC, billypchan commented
@typfel I will try to move this workflow to organisation level. Ref: https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
We can merge this PR first and then create a new PR for moving workflows

2021-11-22 10:56 UTC, typfel approved these changes

2021-11-22 10:56 UTC, merged