chore: Restore self-deleting messages SQSERVICES-1059
wireapp/wire-ios-data-model pull request #1293
Opened 2021-11-23 14:22 UTC by KaterinaWire

<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/SQSERVICES-1059" title="SQSERVICES-1059" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/secure/viewavatar?size=medium&avatarId=10818&avatarType=issuetype" />SQSERVICES-1059</a>  Restore self-deleting messages
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?
Restore self-deleting messages

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2021-11-23 14:45 UTC, johnxnguyen requested changes

2021-11-23 14:45 UTC, johnxnguyen commented on Patches/InvalidConversationRemoval.swift
> +            zmLog.safePublic("Failed to batch delete entities: \(error.localizedDescription)")
Changes in this file should be reverted too.

2021-11-23 14:45 UTC, johnxnguyen commented on Patches/PersistedDataPatches.swift
> +        let currentVersion = "278.0.0"
I think a comment is needed here just to explain the situation, something like "Normally we fetch the short version from the framework bundle, but it's not working so we hardcode the version.

2021-11-23 14:45 UTC, johnxnguyen commented on Resources/Configurations/version.xcconfig
> +CURRENT_PROJECT_VERSION = 272.0.2
You can also bump these, even though they're not being used.

2021-11-23 16:33 UTC, KaterinaWire commented on Resources/Configurations/version.xcconfig
> +CURRENT_PROJECT_VERSION = 272.0.2
Fixed

2021-11-23 16:33 UTC, KaterinaWire commented on Patches/PersistedDataPatches.swift
> +        let currentVersion = "278.0.0"
Added comment

2021-11-23 16:34 UTC, typfel approved these changes

2021-11-23 16:39 UTC, KaterinaWire commented on Patches/InvalidConversationRemoval.swift
> +            zmLog.safePublic("Failed to batch delete entities: \(error.localizedDescription)")
Done

2021-11-24 07:46 UTC, johnxnguyen approved these changes

2021-11-24 08:12 UTC, KaterinaWire commented
release major

2021-11-24 08:13 UTC, merged