refactor: ZMUser from Objc to Swift #SQCORE-1157
wireapp/wire-ios-data-model pull request #1294
Opened 2021-11-26 17:00 UTC by sb88k

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

ZMUser class is written in Objective-c, and we want it to have it in Swift.

Please suggest if you have better idea on anything.

2021-11-29 14:22 UTC, typfel requested changes
Looks good! We should create a playground build with these changes and have QA run a regression run against it before merging though.

2021-11-29 15:01 UTC, sb88k commented on Source/Model/User/ZMUser+RichProfile.swift
> +@objc public class ZMUserKeys: NSObject {
Yes `RichProfile` exists twice.

I wanted to ask if there is a better way to manage those keys.

To keep it as enum, It needs to be Int enum. I tried struct and it didn't work.
As [this](https://stackoverflow.com/questions/26463487/swift-globals-and-global-functions-in-objective-c) article says I need to use class conforming to NSObject to make it usable in objc. (because still there are large code base still using ZMUser in objc)

I couldn't find the Apple document which the article above saying, but this was the way how I made it work.

And, where it is possible, I am trying to use `#keyPath` instead of the defined keys.

2021-11-29 15:02 UTC, sb88k commented on Source/Model/User/ZMUser+RichProfile.swift
> +@objc public class ZMUserKeys: NSObject {
Also, because of the keys, there will be some changes in RequestStrategy, SyncEngine,(or/and ShareEngine) and the UI code.

2021-11-30 09:13 UTC, typfel commented on Source/Model/User/ZMUser+RichProfile.swift
> +@objc public class ZMUserKeys: NSObject {
I think moving the keys to `ZMUser` sounds reasonable combined with using #keyPath when possible.

2021-11-30 09:33 UTC, sb88k commented on Source/Model/User/ZMUser+RichProfile.swift
> +@objc public class ZMUserKeys: NSObject {
I tried to have it as global variable just like how it is done in UserClient.
It works with Swift code but, since objc cannot access Swift's global variable, it does not work with objc code in other places.
Let me move those into ZMUser.

2021-12-02 13:27 UTC, typfel approved these changes
Let's disable the tests which doesn't work on iOS 15 https://wearezeta.atlassian.net/browse/SQCORE-1188

2021-12-03 07:37 UTC, johnxnguyen approved these changes
Looks good to me!

2021-12-22 18:20 UTC, sb88k commented
Might need more time to properly finish this task.

I have been trying to build and provide a playground build to QA for running the regression test.
But, because of `MockUser` in UI project test is causing little problem with this refactoring.

Both `MockUser` and `ZMUser` conform to `UserType`, and I guess when `ZMUser` is written in objc, it is possible to cast to each other. But, now, Xcode is complaining that `MockUser` cannot be casted to `ZMUser`.

So, I will spend little more time to understand how the mock user works, and then, I will proceed further action.

2021-12-28 11:33 UTC, sb88k commented
<img src=https://user-images.githubusercontent.com/13096974/147561589-bce3e00c-37e6-4cd6-b2b9-6d75e5d857d4.png width=49%> <img src=https://user-images.githubusercontent.com/13096974/147561798-29be7eed-5d66-4c76-af10-921f5d7b5023.png width=49%>

So, the code on the left in objc works and the code on the right in swift does not work.

I tried to convert `MockUser` into swift and have all the return type and the type in the test logic to use the common protocol which is `UserType`, but there are some missing properties from `UserType`, such as `team` and `membership`. 
It would work if I add those missing properties in `UserType` and `MockUser`, but `UserType` is not a class only for testing, so I would discuss it to find the better way to make this happen.

2023-09-25 19:51 UTC, closed without merging