refactor: Convert ZMConversation Objc to Swift #SQCORE-1158
wireapp/wire-ios-data-model pull request #1299
Opened 2021-12-06 13:28 UTC by sb88k

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Convert ZMConversation entity code from Objc to Swift.

2021-12-06 13:39 UTC, sb88k commented on Tests/Source/Utils/RolesMigrationTests.swift
>          selfConvo.userDefinedName = "Self"
@typfel 
This test case is still failing due to the missing self conversation.
And I think the base class is not creating the self conversation.

I ran this with objc code and `selfConvo` here is pointing `0x00000000`, so I guess the asserts related to `selfConvo` below are not really working.
Also, two test cases in sync engine, `testThatEventsAreForwardedToAllEventConsumers_WhenProcessed` and `testThatItProcessBufferedEvents_WhenSyncCompletes`, are failing because of the same reason.

so, my assumption is that the self conversation should be created along with some object together, but I could not find any clue.

If we change `selfConversation(in:)` function to return optional ZMConversation, it will cause a lot of changes in all over the places in the consumers, also unexpected behaviors.

2021-12-06 14:00 UTC, typfel commented on Tests/Source/Utils/RolesMigrationTests.swift
>          selfConvo.userDefinedName = "Self"
When you run the real application we always have a self conversation because it's created by the BE which we then synchronise.

I agree that changing  `selfConversation(in:)` to return an optional ZMConversation would cause a lot of changes.

I think we should fix the tests by explicitly creating the self conversation in the `DiskDatabaseTests` since they seems to expect it to be there.

2021-12-14 08:36 UTC, typfel approved these changes
Good work! 🚀 

Also before we merge this we should create playground build and run the automation regression run.

2021-12-14 08:36 UTC, typfel commented on Source/Model/Conversation/ZMConversation.swift
> +    public func append(_ newMessage: ZMMessage?) {
I agree that we should change the signatures of public methods but I think we should take second pass after this PR is merged and see how we can clean up the API.

Here I'd say it's pretty clear that `newMessage` shouldn't be optional since we crash the app if it is.

2021-12-15 08:24 UTC, johnxnguyen requested changes

2021-12-15 08:24 UTC, johnxnguyen commented on Source/Model/Conversation/ZMConversation+Type.swift
> +               localParticipantsExcludingSelf.count == 1 {
If I remember correctly there was a comment here describing that the order of these checks affects performance. I think it would be a good idea to preserve that comment because it's not obvious that changing the order of these calls would be more expensive.

2021-12-18 13:40 UTC, sb88k commented on Source/Model/Conversation/ZMConversation+Type.swift
> +               localParticipantsExcludingSelf.count == 1 {
I will take a look 👍

2021-12-27 10:00 UTC, johnxnguyen approved these changes

2023-09-25 19:51 UTC, closed without merging