fix: do not force unwrap accessError
wireapp/wire-ios-data-model pull request #1308
Opened 2021-12-15 16:15 UTC by billypchan

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Test crashes when running `testThatItStoresAndClearsDatabaseKeyOnAllContexts`

### Causes (Optional)

When on iOS 15 simulator, `accessError` is nil 

### Solutions

Do not force unwrap `accessError`, throw a new case `failedToDecryptDatabaseKeyWithNoError`
In `testThatItStoresAndClearsDatabaseKeyOnAllContexts`, use `XCTUnwrap` to fail earlier when `EncryptionKeys.createKeys` throws

2021-12-15 16:16 UTC, sb88k approved these changes

2021-12-16 09:10 UTC, sb88k approved these changes

2021-12-16 09:24 UTC, typfel requested changes
Let's add reference to https://wearezeta.atlassian.net/browse/SQCORE-1188 which contains the context on why these tests fail on iOS 15.

2021-12-16 09:29 UTC, billypchan commented on Tests/Source/ManagedObjectContext/CoreDataStackTests+EncryptionAtRest.swift
> +            XCTExpectFailure("Expect to fail on iOS 15 simulator.")
```suggestion
            XCTExpectFailure("Expect to fail on iOS 15 simulator. ref: https://wearezeta.atlassian.net/browse/SQCORE-1188")
```

2021-12-16 09:30 UTC, billypchan commented on Tests/Source/Utils/EncryptionKeysTests.swift
> +            XCTExpectFailure("Expect to fail on iOS 15 simulator.")
```suggestion
            XCTExpectFailure("Expect to fail on iOS 15 simulator. ref: https://wearezeta.atlassian.net/browse/SQCORE-1188")```

2021-12-16 09:30 UTC, billypchan commented on Tests/Source/Utils/EncryptionKeysTests.swift
> +            XCTExpectFailure("Expect to fail on iOS 15 simulator.")
```suggestion
            XCTExpectFailure("Expect to fail on iOS 15 simulator. ref: https://wearezeta.atlassian.net/browse/SQCORE-1188")```

2021-12-16 09:30 UTC, billypchan commented on Tests/Source/Utils/EncryptionKeysTests.swift
> +            XCTExpectFailure("Expect to fail on iOS 15 simulator.")
```suggestion
            XCTExpectFailure("Expect to fail on iOS 15 simulator. ref: https://wearezeta.atlassian.net/browse/SQCORE-1188")```

2021-12-16 09:30 UTC, billypchan commented on Tests/Source/Utils/EncryptionKeysTests.swift
> +            XCTExpectFailure("Expect to fail on iOS 15 simulator.")
```suggestion
            XCTExpectFailure("Expect to fail on iOS 15 simulator. ref: https://wearezeta.atlassian.net/browse/SQCORE-1188")```

2021-12-16 09:31 UTC, billypchan commented on Tests/Source/Utils/EncryptionKeysTests.swift
> +            XCTExpectFailure("Expect to fail on iOS 15 simulator.")
```suggestion
            XCTExpectFailure("Expect to fail on iOS 15 simulator. ref: https://wearezeta.atlassian.net/browse/SQCORE-1188")```

2021-12-16 09:32 UTC, billypchan commented on Source/Utilis/EncryptionKeys.swift
> +            let error = accessError?.takeRetainedValue()
```suggestion
            //Notice: accessError is nil when test with iOS 15 simulator. ref:https://wearezeta.atlassian.net/browse/SQCORE-1188
            let error = accessError?.takeRetainedValue()
```

2021-12-16 09:42 UTC, billypchan commented on Tests/Source/Utils/EncryptionKeysTests.swift
> +            XCTExpectFailure("Expect to fail on iOS 15 simulator. ref: https://wearezeta.atlassian.net/browse/SQCORE-1188")```
```suggestion
            XCTExpectFailure("Expect to fail on iOS 15 simulator. ref: https://wearezeta.atlassian.net/browse/SQCORE-1188")
```

2021-12-16 09:42 UTC, billypchan commented on Tests/Source/Utils/EncryptionKeysTests.swift
> +            XCTExpectFailure("Expect to fail on iOS 15 simulator. ref: https://wearezeta.atlassian.net/browse/SQCORE-1188")```
```suggestion
            XCTExpectFailure("Expect to fail on iOS 15 simulator. ref: https://wearezeta.atlassian.net/browse/SQCORE-1188")
```

2021-12-16 09:42 UTC, billypchan commented on Tests/Source/Utils/EncryptionKeysTests.swift
> +            XCTExpectFailure("Expect to fail on iOS 15 simulator. ref: https://wearezeta.atlassian.net/browse/SQCORE-1188")```
```suggestion
            XCTExpectFailure("Expect to fail on iOS 15 simulator. ref: https://wearezeta.atlassian.net/browse/SQCORE-1188")
```

2021-12-16 09:43 UTC, billypchan commented on Tests/Source/Utils/EncryptionKeysTests.swift
> +            XCTExpectFailure("Expect to fail on iOS 15 simulator. ref: https://wearezeta.atlassian.net/browse/SQCORE-1188")```
```suggestion
            XCTExpectFailure("Expect to fail on iOS 15 simulator. ref: https://wearezeta.atlassian.net/browse/SQCORE-1188")
```

2021-12-16 09:43 UTC, billypchan commented on Tests/Source/Utils/EncryptionKeysTests.swift
> +            XCTExpectFailure("Expect to fail on iOS 15 simulator. ref: https://wearezeta.atlassian.net/browse/SQCORE-1188")```
```suggestion
            XCTExpectFailure("Expect to fail on iOS 15 simulator. ref: https://wearezeta.atlassian.net/browse/SQCORE-1188")
```

2021-12-16 09:45 UTC, johnxnguyen approved these changes
It'd be nice to fix the indentation of the `#if` blocks.

2021-12-16 11:37 UTC, typfel approved these changes

2021-12-16 12:47 UTC, billypchan commented
release major

2021-12-16 12:47 UTC, zenkins commented
Hello, @billypchan! Merging PR for command **release major** for PR #**1308**. Will create a **major** release after merged.
Next version is 280.0.0.

2021-12-16 12:47 UTC, merged