feat(mls): replenish key packages FS-793
wireapp/wire-ios-data-model pull request #1399
Opened 2022-08-11 10:26 UTC by ghuMustafa

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

- In this ticket when we call method upload key packages we check if the amount of the remaining key packages is less then 50 % we try to replenish remaining amount of key packages.
- Modified the upload key packages calls with async await.

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-08-12 11:15 UTC, johnxnguyen commented on MLS/MLSController.swift
> +    func uploadKeyPackagesIfNeeded(for clientID: String, with context: NotificationContext) async throws
Where is this being called?

2022-08-12 11:15 UTC, johnxnguyen commented on MLS/MLSController.swift
> +    func uploadKeyPackagesIfNeeded(for clientID: String, with context: NotificationContext) async throws
Also I don't think you need to pass in the context here, you can take it from the `context.notificationContext` in the mls controller.

2022-08-12 11:15 UTC, johnxnguyen commented on MLS/MLSController.swift
> +}
I think it could be confusing to have a getter with additional logic as it could happen you set the the value to one value and then get a different value.

I suggest split the logic across two properties. One stores a `Date` timestamp for the last check, another computes if more than 24 hours has passed since the last check.

2022-08-12 12:09 UTC, ghuMustafa commented on MLS/MLSController.swift
> +    func uploadKeyPackagesIfNeeded(for clientID: String, with context: NotificationContext) async throws
It's bing called from sync engine `UserClientRequestStrategy` after the MLS Public Keys uploaded,
https://github.com/wireapp/wire-ios-sync-engine/pull/1775/files

When I try access context from MLS Controller its crashes while getting clientID 
`let clientID = ZMUser.selfUser(in: context).selfClient()?.remoteIdentifier`
because of calling from Task { } thread.

2022-08-12 12:09 UTC, ghuMustafa commented on MLS/MLSController.swift
> +        let remainingKeyPackagesCountCheck = clientValidKeyPackagesCount < targetUnclaimedKeyPackageCount / 2
Thanks I will rename them

2022-08-12 12:10 UTC, ghuMustafa commented on MLS/MLSController.swift
> +        let clientValidKeyPackagesCount  = 50
Yes thats more descriptive.

2022-08-16 10:03 UTC, David-Henner approved these changes

2022-08-16 12:12 UTC, johnxnguyen requested changes

2022-08-16 12:12 UTC, johnxnguyen commented on MLS/MLSController.swift
> +    var lastKeyPackageStoredDate: Date? {
Perhaps something like `lastKeyPackageCountDate`

2022-08-16 12:12 UTC, johnxnguyen commented on MLS/MLSController.swift
> +    func uploadKeyPackagesIfNeeded(for clientID: String, with context: NotificationContext) async throws
In addition to uploading initial key packages, we should also try to check if we need to do this periodically. At the moment, we only do it when creating a new client, which only happens once. (maybe we we're also doing it when the mls controller initializes?).

Perhaps we can call this method after processing a welcome message, since a welcome message usually means that a key package was consumed. Note that we shouldn't actually upload new key packages after every welcome message received, but we just want to check if we need to upload more (which is what the method is doing).

2022-08-16 12:18 UTC, johnxnguyen commented on MLS/MLSController.swift
> +    func uploadKeyPackagesIfNeeded(for clientID: String, with context: NotificationContext) async throws
> When I try access context from MLS Controller its crashes while getting clientID
let clientID = ZMUser.selfUser(in: context).selfClient()?.remoteIdentifier
because of calling from Task { } thread.

I was referring to the `NotificationContext`. I don't think you need to pass that as an argument, you should be able to get a reference to the notification context from the `context` inside the mls controller. So I suggest to remove it as an argument.

2022-08-19 12:31 UTC, ghuMustafa commented on MLS/MLSController.swift
> +    func uploadKeyPackagesIfNeeded(for clientID: String, with context: NotificationContext) async throws
Yes I have update the arguments for uploadKeyPackages removed the `context` and `clientID` dependancy and also handling the async calls inside of `Task` in the method implementation.

2022-08-26 08:22 UTC, johnxnguyen commented on Tests/MLS/MockMLSController.swift
> +
don't forget to add 

```swift
calls.uploadKeyPackagesIfNeeded.append(())
```

2022-08-26 08:22 UTC, johnxnguyen commented on MLS/MLSController.swift
> +            let keyPackages = try generateKeyPackages(amountRequested: amount)
According to the updated use case, we should always request the target number of key packages.

2022-09-14 11:29 UTC, johnxnguyen reviewed
Looks good. I think we need a test that we check to upload key packages after processing a welcome message. What do you think?

2022-09-14 11:29 UTC, johnxnguyen commented on MLS/MLSController.swift
> +            return false // maybe return true if we want to query the backend even though core crypto threw an error
It probably is a good idea to return true here, to be on the safer side.

2022-09-14 16:47 UTC, David-Henner commented
> Looks good. I think we need a test that we check to upload key packages after processing a welcome message. What do you think?

Yes, good point. I added a simple test to verify this. I also noticed there are no tests for processing the welcome message, so they will need to be added at some point

2022-09-14 16:47 UTC, David-Henner commented on MLS/MLSController.swift
> +            return false // maybe return true if we want to query the backend even though core crypto threw an error
done

2022-09-14 16:49 UTC, David-Henner commented on MLS/MLSController.swift
> +        Task { () -> Void in
We don't

```swift
// doing this made the Task return value ambiguous for the compiler
return Logging.mls.warn("...")
```

2022-09-15 09:49 UTC, merged