Feat/data model patch
wireapp/wire-ios-data-model pull request #1430
Opened 2022-11-21 11:07 UTC by johnranj

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Framework version dependency has to be removed while migrating to monorepo

### Solutions

Added newly added persisted data patch class to remove dependencies of framework version

##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-11-21 11:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wireapp/wire-ios-data-model?pullRequest=1430) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wireapp/wire-ios-data-model?pullRequest=1430) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wireapp/wire-ios-data-model?pullRequest=1430) it.</sub>

2022-11-22 10:09 UTC, johnxnguyen commented on Tests/Source/Utils/PersistedDataPtachesTests.swift
> +    }
As an example:

```swift
func testItRunsPatchesGreaterThanPreviousVersion() {
    // Given
    setPreviousVersion = 5

    var wasPatch1Executed = false    
    let patch1 = TestPatch(version: 4) {
        wasPatch3Executed = true
    }

    var wasPatch2Executed = false
    let patch2 = TestPatch(version: 5) {
        wasPatch2Executed = true
    }

    var wasPatch3Executed = false
    let patch3 = TestPatch(version: 6) {
        wasPatch3Executed = true
    }

    var wasPatch4Executed = false
    let patch4 = TestPatch(version: 7) {
        wasPatch4Executed = true
    }

    TestPatch.allCases = [patch1, patch2, patch3, patch4]

    // When
    Patchapplicator.apply(TestPatch.self, in: self.syncMOC)

    // Then
    XCTAssertFalse(wasPatch1Executed)
    XCTAssertFalse(wasPatch2Executed)
    XCTAssertTrue(wasPatch3Executed)
    XCTAssertTrue(wasPatch4Executed)
}

```

2022-11-28 08:48 UTC, johnxnguyen commented on Patches/PatchApplicator.swift
> +// Copyright (C) 2017 Wire Swiss GmbH
```suggestion
// Copyright (C) 2022 Wire Swiss GmbH
```

2022-11-28 08:48 UTC, johnxnguyen commented on Patches/PatchApplicator.swift
> +
```suggestion
```

2022-11-28 08:48 UTC, johnxnguyen commented on Patches/PatchApplicator.swift
> +        }
```suggestion
        guard let previousVersion = context.persistentStoreMetadata(forKey: lastRunPatchVersion) as? Int else {
            zmLog.info("no previous version found, this is a fresh install, skipping...")
            return
        }
```

2022-11-28 08:48 UTC, johnxnguyen commented on Patches/PatchApplicator.swift
> +        }
```suggestion
        T.allCases
            .filter { $0.version > previousVersion }
            .forEach { $0.execute(in: context) }
```

2022-11-28 08:48 UTC, johnxnguyen commented on Patches/PatchApplicator.swift
> +let lastRunPatchVersion = "zm_lastDataModelVersionThatWasPatched"
```suggestion
let lastRunPatchVersion = "zm_PatchApplicatorLastRunPatchVersion"
```

2022-11-28 08:48 UTC, johnxnguyen commented on Patches/PatchApplicator.swift
> +}
```suggestion
enum DataPatch: Int, DataPatchInterface {

    // Add patches as cases.    
    
    var version: Int {
        return rawValue
    }
    
    func execute(in context: NSManagedObjectContext) {
        switch self {
        }
    }
}
```

2022-11-28 08:48 UTC, johnxnguyen commented on Source/ManagedObjectContext/NSManagedObjectContext+Patches.swift
> +        //when we move to the monorepo, run the 'PatchApplicator' here.
```suggestion
        // When we move to the monorepo, run the 'PatchApplicator' here.
```

2022-11-28 08:48 UTC, johnxnguyen commented on Tests/Source/Utils/PatchApplicatorTests.swift
> +    let block: (NSManagedObjectContext)->()
```suggestion
    let block: (NSManagedObjectContext) -> ()
```

2022-11-28 08:48 UTC, johnxnguyen commented on Tests/Source/Utils/PatchApplicatorTests.swift
> +        print("executing test patch")
```suggestion
        block()
```

2022-11-28 08:48 UTC, johnxnguyen commented on WireDataModel.xcodeproj/project.pbxproj
> +				874B5DA91CEDB9E40010474C /* Cartfile.private */,
Why did this file move?

2022-12-09 09:19 UTC, johnxnguyen approved these changes

2022-12-13 15:47 UTC, johnxnguyen commented on Tests/Source/Utils/PatchApplicatorTests.swift
> +    let applicator = PatchApplicator(lastRunVersionKey: "zm_PatchApplicatorLastRunPatchVersion")
You should create the applicator (in this case it should be called `sut`) in the setup so it's brand new for each test.

2022-12-13 15:47 UTC, johnxnguyen commented on Patches/PatchApplicator.swift
> +    init(lastRunVersionKey: String) {
This should be public if it is to be created outside of the data model framework.

2022-12-13 15:47 UTC, johnxnguyen commented on Patches/PatchApplicator.swift
> +class PatchApplicator {
This should be public if it is to be created outside of the data model framework.

2022-12-19 11:38 UTC, johnxnguyen requested changes

2022-12-19 11:38 UTC, johnxnguyen commented on Patches/PatchApplicator.swift
> +    ) {
I think we made a mistake here: this method shouldn't be generic. It should have a signature like:

```swift
public func applyPatches(in context: NSManagedObjectContext)
```

2023-01-03 11:15 UTC, johnxnguyen approved these changes

2023-01-03 11:33 UTC, johnxnguyen commented
release major

2023-01-03 11:33 UTC, zenkins commented
Hello, @johnxnguyen! Merging PR for command **release major** for PR #**1430**. Will create a **major** release after merged.
Next version is 295.0.0.

2023-01-03 11:33 UTC, merged